### ISSUE TITLE
SMARTY language support?

### ISSUE THREAD

**Issue by mattez** [aaron-bond/better-comments#100]
Please add SMARTY template language support? It's oldschool but we still use it
SMARTY comment looks like this:
`{* this is a comment *}`
See documentation at [SMARTY comments syntax docs](https://www.smarty.net/docs/en/language.basic.syntax.tpl#language.syntax.comments).

We use it like:
`{* TODO: this should be done *}`

**Comment by aaron-bond** [comment]
This works now as of v3.
