### ISSUE TITLE
JSDoc block content highlighted as "important"

### ISSUE THREAD

**Issue by Ladonasc** [aaron-bond/better-comments#101]
Hi o/

first of all thanks for your extension which is clearly useful to isolate meaningful comments.

Recently I saw that my JSDoc block content are all highlighted using the "important" color :

![screen shot 2018-09-26 at 15 05 50](https://user-images.githubusercontent.com/12127351/46081928-0e143900-c19e-11e8-9f0e-797bebf0a0c5.png)

I'm quite sure that a few days ago (or weeks ?) these typical JSDoc block were not highlighted like this, is it a bug ?

**Comment by aaron-bond** [comment]
Hi there. This is definitely caused by the v2 release. I was afraid this would happen!

Thanks for the heads-up. I'll get this resolved ASAP :)

**Comment by Ladonasc** [comment]
Good to know, thanks for your work ;)

**Comment by aaron-bond** [comment]
As expected, caused by the changes to block comment parsing logic. Fixed by always expecting a space or end-of-line after the block comment opening.
Thanks again for catching this one :)
