### ISSUE TITLE
Haskell support for multi-line comment

### ISSUE THREAD

**Issue by QuietJoon** [aaron-bond/better-comments#102]
I've tried your plug-in for Haskell, and I've got some trouble with multi-line support.

One-line comment works well, and when I add one-line comment inside fo multi-line comment, it also works.

![haskell-multi-line-support](https://user-images.githubusercontent.com/2800434/46112357-66dae480-c225-11e8-82ed-6b5b31a7c14a.jpg)

**Comment by aaron-bond** [comment]
Block comments in Haskell aren't supported as of the latest release. I'll get this fixed for the next release
