### ISSUE TITLE
Coloring tag doesn't work like README

### ISSUE THREAD

**Issue by QuietJoon** [aaron-bond/better-comments#103]
I've tried commenting like README.md, but tag color does not appear when the `*` is placed in front of other tag.
![sample-support](https://user-images.githubusercontent.com/2800434/46112568-013b2800-c226-11e8-96ee-ceee347601f1.jpg)

I have no problem with this situation, but I thought I misconfigured something about the plug-in for a day.
The picture of README.md may be changed.

**Comment by aaron-bond** [comment]
Hi there. If you're using JSDoc style comments you put `*` at the beginning of each line in the block comments. This looks like this:
`/**
   * ! this goes red
   */`

Notice the `/**`. If you use the other style of block comment `/*` you don't need the `*` on each line. This is in line with common block style in JS

**Comment by Jacajack** [comment]
Hi, do you think it would be possible to customize this behavior?

For example, I use `/**` to begin my Doxygen comments and I don't use `*` on each line. Doxygen also accepts `/*!` as beginning of a block comment, but it seems it doesn't work either.

<img height=400em src=https://user-images.githubusercontent.com/6173262/46234483-cdbbe300-c376-11e8-8b9a-8d6063af1999.png></img>

Thank you for consideration in advance

**Comment by Jacajack** [comment]
I tried reading the parser code, to see if I could help somehow, but I don't really understand Typescript very well, so I'm afraid there's nothing I can do, at least when it comes to pull requests. Take your time to think it through, though.

My only thought so far is to write some super-crazy regex that only matches JSDoc comments (and therefore ignores the asterisks) if **every** line begins with `*` and the opening tag matches `/**`. That doesn't seem to be the right nor really foolproof way to do it. What do you think?

**Comment by jagretz** [comment]
Do this, 
```json
    {
      "tag": "todo",
      "color": "#FF8C00",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "* todo",
      "color": "#FF8C00",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
    {
      "tag": "/* todo",
      "color": "#FF8C00",
      "strikethrough": false,
      "backgroundColor": "transparent"
    },
```
and you get 
![fixed_it](https://user-images.githubusercontent.com/7716063/47178007-f4bb6400-d2e7-11e8-936b-a1f7d3185232.PNG)
