### ISSUE TITLE
HELP: Show on scroll bar

### ISSUE THREAD

**Issue by emilmirzayev** [aaron-bond/better-comments#104]
Hi Aaron,

thank you for this awesome plugin. Is it possible to make it to show the colored version of comments also on the scroll bar?
Like red ones also are shown as a red dot or so ?
It is so for errors in code, they are being caught by linter and shown as red. Can it be possible to have similar feature? 
Something like this? God level Photoshopped

![image](https://user-images.githubusercontent.com/25964049/46152796-0c1baa00-c272-11e8-9521-a5e0aa192deb.png)

**Comment by aaron-bond** [comment]
Hi @emilmirzayev, loving the graphics work there!

Looks like this was raised on #106 also. I'll close this one off and track it with #106.

Thanks :)
