### ISSUE TITLE
support for asciidoc files?

### ISSUE THREAD

**Issue by ecarter-isp** [aaron-bond/better-comments#107]
Could you add support for AsciiDoc files? 
Asciidoc comment lines begin with "//" and the delimiter for multi-line comments is "////".

Thanks!

**Comment by aaron-bond** [comment]
Hi there. I've never heard of AsciiDoc files before. How does that block syntax work? What's the ending delimiter?

**Comment by ecarter-isp** [comment]
Hi there.    Block comments begin and end with //// on a line by itself.   
  
 https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#comments
  

  
  

  
  
>
