### ISSUE TITLE
Extension Not Working Properly with CSS Files

### ISSUE THREAD

**Issue by glennkojohnst** [aaron-bond/better-comments#109]
This is a great extension overall, but I cannot seem to get this extension working with CSS files on a Mac when pressing press command + / and then any of the tags like ! at the beginning of a line of code. Same thing when I manually type: /* ! */ there is no formatting applied. 

The extension works properly in HTML and JS fies. I don't use any other languages in VSCode.

Here are my customized settings. The defaults also do not work CSS.

    "better-comments.tags": [{
            "tag": "!",
            "color": "#fff",
            "strikethrough": false,
            "backgroundColor": "FF2D00"
        },
        {
            "tag": "?",
            "color": "#3498DB",
            "strikethrough": false,
            "backgroundColor": "transparent"
        },
        {
            "tag": "//",
            "color": "#474747",
            "strikethrough": true,
            "backgroundColor": "transparent"
        },
        {
            "tag": "todo",
            "color": "#fff",
            "strikethrough": false,
            "backgroundColor": "FF8C00"
        },
        {
            "tag": "*",
            "color": "#98C379",
            "strikethrough": false,
            "backgroundColor": "transparent"
        }
    ]

**Comment by aaron-bond** [comment]
Yeah this is a bug. @pim-moeskops is right about the activation string. I'll get this sorted :)

**Comment by glennkojohnst** [comment]
Thanks for the quick reply!

**Comment by glennkojohnst** [comment]
Thanks for the quick turnaround on this. How do I downloaded the updated package? I'm new to the world of GitHub.

**Comment by aaron-bond** [comment]
You won't need to :)

I'll be pushing the extension to the market when I finish a few more bugs (probably in an hour or so) and then you'll get the update automatically through VSCode.

**Comment by glennkojohnst** [comment]
Awesome. Thanks

**Comment by viT-1** [comment]
Same bug for *.less files
