### ISSUE TITLE
Feature Request: Add settings for modifying annotation indicators

### ISSUE THREAD

**Issue by SidIcarus** [aaron-bond/better-comments#11]
Rationale: Allow those who follow JSDoc or similar documentation conventions, `@` to have highlighting.

Current:
- Alert: `!`
- Queries: `?`
- Todo: `TODO`
- Removed: `////`
- Description: ` ` (none?) 

Proposed: (defaults written in) 
```
better-comments.annotations: {
  alert: ['!'],
  queries: ['?'],
  todo: ['TODO'],
  removed: ['////'],
  description: [' '],
}
```
I suggest an array so that if people want to have multiple annotations be highlighted identically, such as both ['TODO', '@todo', '@TODO'], it'll be feasible.

**Comment by aaron-bond** [comment]
This FR kicked off an absolute brain fart of a changeset, but it got there eventually. See: https://github.com/aaron-bond/better-comments/commit/0e7eab9d352780bfb303caf090e186c15bdcc77b

Push to marketplace coming ASAP
