### ISSUE TITLE
No params appear for JavaScript arrow functions

### ISSUE THREAD

**Issue by kaytrance** [aaron-bond/better-comments#114]
When I have arrow function in JavaScript like this:

```js
arrowFunction = (p1, p2) => {
   console.log("this is arrow function");
}
```

if I type `/**` before function name I expect parameters `p1` and `p2` to appear as `@params` section in comment, but they do not:

![example](https://i.imgur.com/xRAVUYw.gif)

I am using MS Code 1.28.2 and BetterComments 2.0.2.

**Comment by aaron-bond** [comment]
Looks like this is a bug in VSCode -> https://github.com/Microsoft/vscode/issues/22264

Better Comments doesn't do the JSDoc templated comments; that's all VScode.
