### ISSUE TITLE
Why no coloring in comments like /* ... */ in .h files

### ISSUE THREAD

**Issue by FlyGinger** [aaron-bond/better-comments#122]
I mean that the plugin doesn't work for C language's single line comment. For example,
```C
int a = 0; /* ! blah blah blah */
```
Thank you for you amazing plugin.

**Comment by FlyGinger** [comment]
Is it caused by wrong configuration of myself?

**Comment by aaron-bond** [comment]
Hi there. In order for block comment and single line comment syntax to work at the same time, the parser expects a block comment to always span multiple lines. If you use `//` instead you'll get the highlighting like you would expect

**Comment by FlyGinger** [comment]
Got it. Thank you.
