### ISSUE TITLE
python @param processing isn't functional 

### ISSUE THREAD

**Issue by ichibrosan** [aaron-bond/better-comments#124]
A multiline block comment preceding a function definition contains an @param annotation like the app page, but it doesn't highlight.
import os
import pprint

"""
myfunc
TODO: work on this
! hello
* hello
@param myparam a parameter
"""
def myfunc(myparm):
    print("Hello World!!")      # TODO this code is ok
    pprint.pprint(os.environ)

myfunc("Hello")

**Comment by aaron-bond** [comment]
This extension doesn't add support for @param. In the readme file, the highlight you're seeing is part of JSDoc comment highlighting. There might be other language services for the language you're using here that does the same thing, but this extension doesn't have it right now
