### ISSUE TITLE
Feature Request: Better support for "doc block"-style multi-line comments

### ISSUE THREAD

**Issue by glek** [aaron-bond/better-comments#13]
At present, having a "doc block"-style multi-line comment produces the following:

![image](https://user-images.githubusercontent.com/1039449/31829877-92a1e948-b58c-11e7-9e69-8fd1c8ea1081.png)

While this is "okay", it's not desirable to have all these lines highlighted. Ideally, it should look more like this:

![image](https://user-images.githubusercontent.com/1039449/31829970-d6bf917a-b58c-11e7-9d08-09c642cea86d.png)

**Comment by aaron-bond** [comment]
Ah interesting catch. I'll take a look
