### ISSUE TITLE
csharp comments does not working

### ISSUE THREAD

**Issue by masteor** [aaron-bond/better-comments#131]
when I edit the cshtml file in vs code your extention does not work, if I rename the csthml file in js - your extention starts to work right away, I ask you to make the extention also work in cshtml files, or make it possible to specify in the program settings what file extensions will the extention work with

**Comment by aaron-bond** [comment]
Multiple languages is a problem for the extension. Related to #129

I don't have any great ideas about how to handle this one. Suggestions welcome.
