### ISSUE TITLE
Support /* ... */ comments

### ISSUE THREAD

**Issue by furier** [aaron-bond/better-comments#134]
Comments like `/* my comment */ ` are not colored unless you add `//` inside the stars, but then the coloring doesn't stop at the end `*/`

![image](https://user-images.githubusercontent.com/776919/52788522-81411d80-3061-11e9-9dc7-43b349e79791.png)

**Comment by metasean** [comment]
@furier - Multiline comments are mostly supported.

First make sure you've enabled "multi-line comments".  You can do so one of two ways:
- navigate to your VS Code settings, do a find on "Better-comments: Multiline Comments" and check the box
- add `"better-comments.multilineComments": true` to your settings.json file.  

I have noticed that it can take several seconds and/or a file change and/or a VS Code reload for the selection to take effect.

Second, the first line doesn't highlight, so ...
```javascript
/* TODO: Will NOT get highlighted */
```
but ...
```javascript
/*
   TODO: Will get highlighted */
```


🤷‍♂️

**Comment by furier** [comment]
mostly but not fully 😄

**Comment by aaron-bond** [comment]
Multiline / block comments are supported when they're on multiple lines.

A block comment on a single line introduces too much messing about for the regex parser and didn't seem to be worth supporting when the single line alternatives exist. Exceptions to this are languages like HTML where the block is the _only_ type of comment.

**Comment by viT-1** [comment]
Native CSS supports only block comments, LESS suppotrts both.

**Comment by FiredLight** [comment]
Only the first line in the block is highlighted:

`
/*
  TODO: I'm highlighted :)
  I'm not highlighted :(
`

Is this due to regex complexity as well?
