### ISSUE TITLE
tags customisation is not working properly

### ISSUE THREAD

**Issue by miguel-pinto-prodmad** [aaron-bond/better-comments#138]
I tried to add my own tag configuration on the settings but it's not working correctly. Adding the code bellow will indeed add the new tag and it will be displayed in the comments with the defined color. However, all other "standard" tags already defined by the extension stop working.

"better-comments.tags": [
    {
      "tag": "#",
      "color": "#aeff00",
      "strikethrough": false,
      "backgroundColor": "transparent"
    }
]

The @param tag (editor default?) is not rendering with any other colors either (just the plain comment color)

**Comment by baanaan** [comment]
Same here for me with both of your issues..

**Comment by aaron-bond** [comment]
Yeah this is a replacement of the existing ones. You'll need to bring across all the ones you want to keep into that array, too.

The intention here is that if someone wants to turn a certain tag off they can just remove it from the list
