### ISSUE TITLE
Feature Request:  Add provisions for Multi-line PowerShell comments

### ISSUE THREAD

**Issue by mpearon** [aaron-bond/better-comments#14]
Please add provisions for multi-line PowerShell comment blocks.
Multi-line comment blocks in PowerShell begin with `<#` and end with `#>`.

Please see [this thread](https://github.com/aaron-bond/better-comments/issues/9) for background.

[Added FR as per @aaron-bond](https://github.com/aaron-bond/better-comments/issues/9#issuecomment-349484207)

**Comment by aaron-bond** [comment]
Thanks for this. I'll take a look at this - I'm a little worried it'll open up a can of worms WRT other multiline comments, but I'll keep an open mind.


Check out the update on the market for the single-line PowerShell support and let me know if you find any issues :)
