### ISSUE TITLE
Coloring not activating without opening settings

### ISSUE THREAD

**Issue by MatthewDudley** [aaron-bond/better-comments#140]
I have to open my settings every time I want to view the colors I have setup. Am I missing something? Is anyone else experiencing this? This extension is great other than this issue for me at least.

**Comment by aaron-bond** [comment]
Do you mean after you change the colors or just any time you open VSCode?

The activation event for the extension is the opening / viewing of a file: the language code is detected and the regex parser is kicked off. Is this the part that isn't working for you?
