### ISSUE TITLE
Language support: Apex

### ISSUE THREAD

**Issue by alexandrgoryachko** [aaron-bond/better-comments#143]
Can you please add support for Apex language?

The syntax for comments are as follow:
- line comment: //
- block comment: /* */
- apex doc: /** */

Apex files end with the .cls file extension.

Many thanks for your great extension and your great job!

**Comment by bmodeprogrammer** [comment]
Yes, this would be great. Thanks @alexandrgoryachko for the ideia. I'm also waiting for this.

And thanks @aaron-bond for the great job of this project.
