### ISSUE TITLE
Language support: GenStat

### ISSUE THREAD

**Issue by PaulGoedhart** [aaron-bond/better-comments#149]
Dear Aaron,

Would you be so kind to add support for the GenStat language (a statistical package by www.vsni.co.uk). GenStat files have the .gen or .gpi extension. Comments are as follows:
line comment: \ comment
block comment: " block comment "

Many thanks!

**Comment by PaulGoedhart** [comment]
I just learned that none of the currently supported languages has the GenStat comment style. However SmallTalk uses the same block comment style! And Forth (and GFort) uses the same line comment.

**Comment by aaron-bond** [comment]
This should be trivial to add but I've not been able to find any sample code to use as a test. Would you be able to provide some?

**Comment by PaulGoedhart** [comment]
Here is an example. Thanks!
![Capture2](https://user-images.githubusercontent.com/49990843/57780971-91809b80-7729-11e9-8b45-d0eae1f9ccfc.JPG)

**Comment by PaulGoedhart** [comment]
Sorry; too hasty. Line comments should start at the beginning of a line. Here is the code to test:
print 0
\ Line comment only at the start of a line
     \ Line comment only at the start of a line
print 2   " Block comment at the end of a line "
print 3   " Block comment at the end of a line 
possibly continuing to the next line
"
print 4
"=============================================================================
 Long block comment
=============================================================================="
print 5
" Another block comment"
print 6
![Capture2](https://user-images.githubusercontent.com/49990843/57781457-824e1d80-772a-11e9-9bf0-1b5ac564c2b5.JPG)
