### ISSUE TITLE
Highlighting not supported on single quote Python docstrings

### ISSUE THREAD

**Issue by jadchaar** [aaron-bond/better-comments#152]
<img width="290" alt="Screen Shot 2019-05-08 at 12 46 46 PM" src="https://user-images.githubusercontent.com/7388203/57392679-6fb67000-718f-11e9-85dd-a8d230b9fb9e.png">

As shown above, if the first line is a TODO comment, for some reason it is not highlighted in the editor. If I push the comments down one line (e.g. so that the first comment is on line 2), then it highlights as usual.

**Comment by ChristianPredebon** [comment]
Hi, excuse me for the intrusion (I came here for the same reason long ago) but from what I can see [here](https://github.com/aaron-bond/better-comments/blob/086c7ea45334a3d545aa8d75f44a2f4ba46ad7ca/src/parser.ts#L37) and [here](https://github.com/aaron-bond/better-comments/blob/086c7ea45334a3d545aa8d75f44a2f4ba46ad7ca/src/parser.ts#L311) it has been a deliberate thing
For more info have a look at [this source](https://stackoverflow.com/questions/2429511/why-do-people-write-the-usr-bin-env-python-shebang-on-the-first-line-of-a-pyt).
Hope it helps, bye.

**Comment by jadchaar** [comment]
Ah that totally makes sense. Thanks.

**Comment by aaron-bond** [comment]
Hi there, sorry for the lack of response.

This is intentional. I had quite a few bug reports when python support was added that the first line (usually an import I think?) was being coloured unintentionally. Unfortunately, with no way to determine whether the user meant it or not, I thought the most sensible option was to turn it off

**Comment by jadchaar** [comment]
Thinking about it, for Python, don't you only need to worry about if someone puts a `# !` scheme to indicate importance in the comment? The regular comment with a `#` followed by `TODO` should be fine since it does not indicate a shebang correct?

Correct me if I am wrong :)

**Comment by aaron-bond** [comment]
Yep you're exactly right. It's worth noting though that the comment delimiters (!, Todo, etc.) are user-configurable. Checking for a specific one for a specific language is something I've tried to avoid for other problems too. Keeping it simple has limited how many things can go wrong :)

**Comment by jadchaar** [comment]
I agree, the decision is probably for the better. @aaron-bond any plans to add support for multi-line comments like Python docstrings?

**Comment by aaron-bond** [comment]
I'm pretty sure they should work today unless there's a bug: https://github.com/aaron-bond/better-comments/blob/086c7ea45334a3d545aa8d75f44a2f4ba46ad7ca/src/parser.ts#L312

**Comment by jadchaar** [comment]
Ah yes it works if double quotes are used in docstrings, but personally I use single quotes in my docstrings so that is why I thought it was not working. Would it be possible to add support for single quote doc strings?

<img width="99" alt="Screen Shot 2019-05-10 at 1 43 12 PM" src="https://user-images.githubusercontent.com/7388203/57545917-b213b480-7329-11e9-9185-6f23deeb9b1f.png">

**Comment by aaron-bond** [comment]
Ah! Interesting. I didn't realise both were allowed. Hmm, most languages support one mechanism for single line and another for multi - don't think any others have 2 sets like this.

Will need to think on it to see if there's a way to do it

**Comment by jadchaar** [comment]
Thanks! I guess I will reopen this issue then. Here is a reference on why both are allowed: https://stackoverflow.com/questions/13081178/the-difference-between-three-single-quoted-and-three-double-quoted-docstrings.

**Comment by aaron-bond** [comment]
Without adding an alternate set of comment tags to every language I'm not sure about a neat way of solving this one. I'm all for K.I.S.S so any ideas you might have to get this working while not ballooning the complexity would definitely be appreciated :)

**Comment by aaron-bond** [comment]
Closing this out as I've no reasonable alternative here without ballooning the scope of the regex. Will keep it in mind if any future requests come in
