### ISSUE TITLE
What's JSON with comments? 

### ISSUE THREAD

**Issue by RbBtSn0w** [aaron-bond/better-comments#153]
README file was supported JSON with comments.

Can you give an example or document?

**Comment by RbBtSn0w** [comment]
Search by self.
https://komkom.github.io

**Comment by aaron-bond** [comment]
It's just JSON files but VSCode will allow you to add comments into them. However, most of the time I've found the comments to corrupt any tools I have reading the JSON, so be careful trying to use it. The tool needs to support reading that file format or else it will break.

NOTE: you can change the language highlighting in VSCode by hitting F1 and typing language - you can then set it to whatever you want, including JSON with comments
