### ISSUE TITLE
How do i edit better-comments.tags

### ISSUE THREAD

**Issue by randy918** [aaron-bond/better-comments#155]
I want to make my own, and see suggestions here on what I could change...but how do I get to the "better-comments.tags" file or location so I can edit or replace it?

**Comment by aaron-bond** [comment]
If you open the settings (F1 > user settings) and search for "better comments" there's an option to copy the config to your local JSON

**Comment by randy918** [comment]
I went there, there were two check mark options for better comments then "better-comments.tags" with the 5 sets. I copied that to my settings.json, ,changed a couple colors to black to test it, restarted VSC and I see no changes yet. 
(was "settings.jason" the wrong one to mess with?

**Comment by aaron-bond** [comment]
Nope, sounds like the right thing. Wanna screenshot it and show me?

**Comment by randy918** [comment]
Thanks, here is a screengrab with my settings.json. You'll see the end of the default settings and the beginning of my added better-comme nt tags. I play around with the hex, save and restart, nothing changes. I also get the settings cant save message 
![5-26-19b settings intro](https://user-images.githubusercontent.com/11927844/58390083-0474f680-7ff5-11e9-99f6-9c2718d7dbd0.jpg)

![5-26-19a settings intro](https://user-images.githubusercontent.com/11927844/58390021-992b2480-7ff4-11e9-846b-8ebd2650be9f.jpg)

**Comment by aaron-bond** [comment]
You've malformed your JSON. It's key/value pairs with commas separating. Move the better-comments block inside the main `{}` block instead of outside it

**Comment by randy918** [comment]
That worked! and makes sense, I appreciate your time!

**Comment by yuvrajjj17** [comment]
I am trying to change the tag instead of "!" to "$" this but still on default tag, why ???

<img width="923" alt="better comment" src="https://user-images.githubusercontent.com/87069437/227051118-bb824006-001f-4527-be1a-a4c93b2c4043.PNG">
