### ISSUE TITLE
Options warning

### ISSUE THREAD

**Issue by eugene-chr** [aaron-bond/better-comments#16]
Expected object instead of array.

"better-comments.tags": [
        {
            "tag": "!",
            "color": "#FF2D00",
            "strikethrough": false
        },
        {
            "tag": "?",
            "color": "#3498DB",
            "strikethrough": false
        },
        {
            "tag": "//",
            "color": "#474747",
            "strikethrough": true
        },
        {
            "tag": "todo",
            "color": "#FF8C00",
            "strikethrough": false
        },
        {
            "tag": "*",
            "color": "#98C379",
            "strikethrough": false
        }
    ],

**Comment by aaron-bond** [comment]
Did you take this from the README? That's my bad. Check out the package.json instead for the proper format. I'll get the README updated soon
