### ISSUE TITLE
How to do multiline comments

### ISSUE THREAD

**Issue by tomasbonco** [aaron-bond/better-comments#163]
Hi!

First of all, I love the extension. It helps me, besides other things, better document my code. One thing that bothers me is how to make proper multiline comments. In order to do that I was prefixing every single line, like this:
```
! It's very important it works the way it works.
! Explanation of relationships and the bigger picture.
! List of everything I was considering when I wrote the code.
```
But it's not very practical when doing `TODO` comments. In the settings and docs, I found that extension somehow supports multiline comments, but I can't find how exactly. Here is my latest try after reading other issues:

<img width="692" alt="Screenshot" src="https://user-images.githubusercontent.com/4013047/59912964-80593780-9417-11e9-8b78-bb84b062b5eb.png">

So my question is - how to do proper multline comments?

**Comment by aaron-bond** [comment]
To use multiline comments you need to either do the `TODO` on each line within the multiline or use JSDoc comments like:
```
/**
 * TODO: hello world
 */
```

**Comment by tomasbonco** [comment]
Hi, even if I use JSDoc style, the comment is colored only on the first line.

**Comment by chrisdhanaraj** [comment]
@aaron-bond Just checking - is there a specific syntax for multi-line comments of the same type? i.e.

```
/**
 * TODO: My very long to do note which 
 * goes onto a second line
*/
```
