### ISSUE TITLE
How to add tags like @param, @return?

### ISSUE THREAD

**Issue by chempyro** [aaron-bond/better-comments#164]
I love this extension and really would like to add tags like @param where there are two or three colors on one line:
/**
\* @param *parameter* The reason this param exists
\* @return *bool* if parameter is equal to 4
*/

I saw this on the README.md, so I thought it might be possible:
![image](https://user-images.githubusercontent.com/48738730/59972089-aed13280-953d-11e9-972c-5129520bf292.png)
Sorry if this is stupid. I haven't seen this anywhere else in the issues however, and I don't know how to edit the JSON in such a way to add this.

**Comment by tomasbonco** [comment]
Hi!
@params and @return are colored by VS Code by default. You have to start your comment with `/**` and then every line ` *` (= regular JSDoc).

**Comment by chempyro** [comment]
So, I'm stupid. It seems to be my color theme. Also, VSCode has something against doing this commenting for Rust, for some reason I don't know. Here's typescript vs rust (default theme):
![Screen Shot 2019-06-24 at 8 50 46 AM](https://user-images.githubusercontent.com/48738730/60033336-3e213780-965d-11e9-92f7-55cd258cbc42.png)
![Screen Shot 2019-06-24 at 8 51 49 AM](https://user-images.githubusercontent.com/48738730/60033381-54c78e80-965d-11e9-9970-cc8179b8ba45.png)
