### ISSUE TITLE
Bug: Parses comment tokens inside of strings

### ISSUE THREAD

**Issue by garrettgsb** [aaron-bond/better-comments#167]
Treats comment tokens as actual comments inside of strings. This is bad news for something like hex codes or hash tags... Example: 

![python-comments](https://user-images.githubusercontent.com/17644767/60131341-00500c00-974e-11e9-815f-e0176f5686a5.png)

The same problem seems to exist in other languages, but `//` comes up a bit less option in Javascript strings, for example, so it's not as big of a deal:

![javascript-comments](https://user-images.githubusercontent.com/17644767/60131225-bc5d0700-974d-11e9-80b9-9fd3a3b636a8.png)

**Comment by aaron-bond** [comment]
Yeah, this has come up on this too: #87 

Closing as a duplicate, but working on a solution
