### ISSUE TITLE
PL/SQL support

### ISSUE THREAD

**Issue by rafael-trevisan** [aaron-bond/better-comments#170]
Hi all,

Has someone else noticed that better-comments stopped working with PL/SQL when using `oracle.oracledevtools`?

**Comment by jtijerina72213** [comment]
The extension changes the language to ".oraclesql" instead of ".plsql", which is not supported.

**Comment by andrzejzysko** [comment]
Now it's working byt only for inline comment.
Multi-line comments does not work for Oracle PL/SQL neither PL/SQL (XYZ).

![image](https://user-images.githubusercontent.com/16927900/92594061-864c6a00-f2a2-11ea-9f51-9b80ceea6f51.png)

**Comment by veranscoto** [comment]
Also sort of having this issue, but I can't even get the inline comments to show up.  File extension seems to be .plsql but comments don't seem to change at all.

**Comment by aaron-bond** [comment]
This is fixed now in v3.
