### ISSUE TITLE
Regular multiline comments where each line starts with asterisk parse incorrectly

### ISSUE THREAD

**Issue by matter123** [aaron-bond/better-comments#177]
When you have a C style multiline comment where each line starts with an asterisk, the comment is parsed as if each line were a highlight. This does not happen when doc style multiline comments (`/**`) are used.

Example:
```
/*
* this isn't supposed to be highlighted
* ? This is a question but is not marked as such
*/

/**
* this isn't supposed to be highlighted
* ? This is a question but is not marked as such
*/
```

![Screenshot from 2019-08-04 09-54-42](https://user-images.githubusercontent.com/714007/62426762-efc07900-b69d-11e9-9548-0a600aa8d7fa.png)

**Comment by aaron-bond** [comment]
This is a result of a choice made to support JSDoc syntax highlighting. Long story, short: we treat `/**` as an intention to use JSDoc and ignore the leading `*` on each line. Otherwise, `/*` is treated as a block comment and the first character of every line is parsed as a highlighting character.

**Comment by matter123** [comment]
The issue is not with the behavior of `/**` doc comments. In C like languages, it is fairly common for non-documentation block comments to start with `*` just like documentation style comments (see the Linux style guide https://www.kernel.org/doc/html/v4.10/process/coding-style.html#commenting).

Without the ability to have better-comments ignore the leading asterisks, the extension becomes useless when working on codebases where that style is common.
