### ISSUE TITLE
Support multi-line comments (mainly TODO)

### ISSUE THREAD

**Issue by Srekel** [aaron-bond/better-comments#18]
See image:

![image](https://user-images.githubusercontent.com/1578924/33929012-3d6d17d2-dfe8-11e7-8469-8cae7df8fb13.png)

I would prefer not to add TODO on the next line because other tools could count that as an additional todo when it's in fact the same as the first.

**Comment by aaron-bond** [comment]
I'm not sure how this would actually work... it would likely need some indication that the comment is actually a continuation of the previous, but that feels like unnecessary complexity?

**Comment by Srekel** [comment]
Mmm. You could check if the lines aligns (like in the screenshot) but I mean, this is not exactly a "must have" feature, more like nice to have. :)

**Comment by aaron-bond** [comment]
As a slight workaround -  perhaps you could add an extra delimiter to your settings with the same color as the TODO? Something like:
```
{
  `tag`: '--',
  `color`: '#FF8C00',
  `strikethrough`: false
}
```
You can have as many of these as you want (in theory).
That way it would all be one color but in the background it's technically two comments?

**Comment by Srekel** [comment]
That's good enough for me. :)
