### ISSUE TITLE
Comments in HTML script tag don't highlight

### ISSUE THREAD

**Issue by tetondev** [aaron-bond/better-comments#181]
I'm finding that comments in a `<script>` tag in an HTML file are not highlighting 😢

![Screen Shot 2019-09-05 at 11 35 40 AM](https://user-images.githubusercontent.com/18534488/64365417-4f79af00-cfd1-11e9-9418-8665521c3965.png)

Thanks for making this extension, love it.

**Comment by aaron-bond** [comment]
![image](https://user-images.githubusercontent.com/14099631/64369069-7953c580-d013-11e9-8978-b756691133a9.png)
Comments in HTML use the angle bracket syntax: https://html.com/tags/comment-tag/

Note: what font are you using? It looks really nice :)

**Comment by tetondev** [comment]
The comments I'm referring to are within a `<script>` tag within an HTML file. Comments within a `<script>` tag would be using the JavaScript comment syntax. In other words, I was anticipating the _better-comments_ extension would be able to detect that there was JavaScript being used despite it being an HTML file. Make sense?

And thanks. The font is called Dank Mono.

**Comment by aaron-bond** [comment]
Ah! Understood.

This is something I've only toyed with so far but I haven't been able to get a workable solution running. The extension uses the file's detected language to figure out which comment structure to parse for, and documents with multiple comment types are currently unsupported. It's something I'm open to some help on.

I'll keep this bug open to track.

**Comment by tetondev** [comment]
Testing it out a bit more I found that if you use JS Docs style multiline comments it actually does detect that it's a JavaScript comment and highlights fine. For some reason, single-line comments or multiline comments (that are not begun with two `**`) are not highlighted under a `script` tag of an HTML file.

It's a decent alternative. Up to you how much you want the other comment types supported in this scenario. I don't mind if you close this issue.

**Comment by mikespnu** [comment]
Jus noticed the same..has there been any progress on this?
