### ISSUE TITLE
Javascript React not auto detecting

### ISSUE THREAD

**Issue by adriantwarog** [aaron-bond/better-comments#19]
When opening up vscode, comment colors are not showing. If i swap my language detection from Javascript React just to Javascript, it begins to work again.

**Comment by aaron-bond** [comment]
Thanks for pointing this out. How can I reproduce this? Do you have a small sample I can run with to see the behaviour?

**Comment by aaron-bond** [comment]
I was missing the activation event for javascriptreact (it's not listed on the VSCode list of language codes...). Should be fixed now :)

**Comment by Logan1x** [comment]
Hey @aaron-bond Where can I find the activation event thing?
