### ISSUE TITLE
Specify in documentation that multiline comments require extra asterisk

### ISSUE THREAD

**Issue by bean5** [aaron-bond/better-comments#196]
**Expected**
Multi-line comments triggerd by `/*` are colorized like the rest.

**Actual**
Only multi-line comments starting with `/**` are colorized.

See also:
![image](https://user-images.githubusercontent.com/2052646/67051211-bffb0c00-f0f7-11e9-8b50-1222c4127257.png)

In other words, I didn't realize this extension is _opinionated_ and expects that JSDoc patterns are used. In the ideal world, TODO and FIXMEs wouldn't even reach documentation, so expecting that a project follow JSDoc patterns seems like a catch-22 (or anti-pattern?).

**Comment by bean5** [comment]
See also: #177

**Comment by bean5** [comment]
Another approach would be to add a setting that is respected at https://github.com/aaron-bond/better-comments/blob/master/src/parser.ts#L191

**Comment by aaron-bond** [comment]
This isn't the case. JSDoc comments expect an asterisk at the start of each line in the block and color depending on the _following_ character; while normal block comments will color for the first character on each line. 
e.g.:
```
/*
  ! alert
  */
```
This is intentional since it gave the most flexibility when the extension first launched and was frequently requested

**Comment by bean5** [comment]
Ah, so it isn't the `/**` that is necessary. It is that I need to remove `*` from being before `! alert`?

I'm still confused because in the picture above, it seemed to be the presence of the second asterisk after the start of the comment.

**Comment by aaron-bond** [comment]
I'll make an update to the ReadMe to make the JSDoc vs normal block comments distinction a bit clearer
