### ISSUE TITLE
Options for alternate style of block comments

### ISSUE THREAD

**Issue by GammaGames** [aaron-bond/better-comments#20]
I'm not sure how much this would be to add, but it would be nice to allow block comments without stars in front of them to have the highlighting. Like this style:
![image](https://user-images.githubusercontent.com/7832163/34492170-a35af8dc-efa3-11e7-9bda-50e09d362217.png)

The options to put the tags right after the /* to make the entire block comment highlighted would be handy as well, to add a strikethrough to an entire block of code or allow multiline todos

**Comment by aaron-bond** [comment]
This was actually the original format expected by the plugin. I changed it a while ago to standardise around JSDoc style comments instead. It would be tricky to allow for * to color a comment in some cases and not on others. Do you use JSDoc style comments at all in your code?

**Comment by GammaGames** [comment]
We actually use that format because it matches python's comment format, and it is what the tool that generates the wiki expects so unfortunately we don't use the standard jsdoc style.

**Comment by GammaGames** [comment]
You know what would be really cool? If instead of using tags at the beginning of the line, the text was styled with markdown. It'd be a standard and then if you parsed your source code for comments for a wiki they would be formatted in both places in the same way

**Comment by aaron-bond** [comment]
Markdown is an interesting idea :)

I think I could maybe add a flag to "useJSDocStyle: boolean" to allow you to turn it off... I will investigate this soon.

**Comment by GammaGames** [comment]
Awesome to hear, thank you!

**Comment by wasifhyder** [comment]
@aaron-bond 

I love this plugin. I've been able to get rid of note-taking applications and move to an entirely text-editor workflow. I would really apprecaite if I could turn the useJSDocStyle to be turned off. Really looking forward to it.

For my usecase, since I use better comments for note taking as well. The JsDoc style gets in the way of being able to fold the code, and affectively different levels of nesting on the note. 

Thanks again! 

I would love to help with this plugin as well, if something comes to mind.

**Comment by wasifhyder** [comment]
Workaround in the meanwhile:

Open extensions folder
Open parser.js
Replace line 24 with the following

Works for me right now :)

```
this.expression = "(" + this.delimiter.replace(/\//ig, "\\/") + ")+( |\t)";
```

**Comment by GammaGames** [comment]
Oops, I forgot to check it last night. I've got a notification now so I'll try to get to looking at it after work! I've never looked at extension code before though, so I don't know how much use I'll be :p

**Comment by aaron-bond** [comment]
Ah OK, no worries :)

I've not found any issues yet myself; all seems to work OK. Just afraid to throw it out there without being confident.

BTW, the way it works now is there's no useJSDoc property; instead, it just works with both right out of the box :)

**Comment by GammaGames** [comment]
I tried to download the extension and compile it on my own so that I could test it and I'm not sure I did it right...
![image](https://user-images.githubusercontent.com/7832163/35178335-ebb6918c-fd44-11e7-8668-cedc07c67265.png)
It has the same version as the repo, and it didn't look like that big of a change in the diffs when I looked at the commits, I'm just not sure what I was looking at. Do you have a packaged version I could install since I might be messing something up?

**Comment by aaron-bond** [comment]
Sure, here's the packaged version. Not sure why getting the code would show anything different :/

[better-comments-1.1.7.zip](https://github.com/aaron-bond/better-comments/files/1648416/better-comments-1.1.7.zip)

**Comment by GammaGames** [comment]
![image](https://user-images.githubusercontent.com/7832163/35178936-75481a30-fd4d-11e7-9d43-ad4dc594be6a.png)
It looks like I was putting stuff in the wrong spots. The basic comment with no highlighting doesn't seem to be working in jsdoc style comments, and it's highlighting the last * before the / in both styles. Those aren't supposed to be happening, are they? Might need more conditions for when to highlight stuff, based on the comment type and stuff

**Comment by aaron-bond** [comment]
Hmm, I thought I caught the last */

As for the JSDoc, the expected start is /** instead of /*

**Comment by aaron-bond** [comment]
Thanks for the heads-up here @GammaGames, I think I've got those issues resolved.

Here is how it currently looks with my test file:
![image](https://user-images.githubusercontent.com/14099631/35184328-0be64f5e-fdec-11e7-879c-a1929c4b5128.png)

And here's the extension file again if you want to try it out with your notes :)
[better-comments-1.1.7.zip](https://github.com/aaron-bond/better-comments/files/1648870/better-comments-1.1.7.zip)

**Comment by GammaGames** [comment]
![image](https://user-images.githubusercontent.com/7832163/35186878-ba2b56d6-fdd8-11e7-8a5d-2443ee50f97f.png)

Looks good with my test now!

**Comment by wasifhyder** [comment]
Will check this in the morning. Thanks a lot @aaron-bond

**Comment by wasifhyder** [comment]
![image](https://user-images.githubusercontent.com/2295057/35193895-121d4d6a-fee5-11e7-8ef8-d1b4ba449053.png)

Works beautifully. Kudos man!
