### ISSUE TITLE
Needs "better comments" summary for opened folder/workspace

### ISSUE THREAD

**Issue by Pra3t0r5** [aaron-bond/better-comments#216]
Pretty much like PROBLEMS window, there should be a specific tab for COMMENTS (much like a TODO list)
![Screenshot from 2020-03-04 12-32-52](https://user-images.githubusercontent.com/38087682/75895474-77c55780-5e14-11ea-8b2b-a2b53731ecdf.png)

**Comment by aaron-bond** [comment]
I made the decision not to add this to the extension - given that each user can configure their own comment formats to highlight, it's something that would be far too comprehensive to add in here.
