### ISSUE TITLE
aaron-bond/better-comments/ and /omsharp/BetterComments

### ISSUE THREAD

**Issue by heartacker** [aaron-bond/better-comments#219]
VS and VSCode is my most code tool. 
seems that the  [`aaron-bond/better-comments/`](https://github.com/aaron-bond/better-comments/) and [`/omsharp/BetterComments`](https://github.com/omsharp/BetterComments) have the  similar rules , it will be better fi compatible with each other  on rule 
:D

**Comment by heartacker** [comment]
@omsharp

**Comment by omsharp** [comment]
Hi @heartacker 

VS Code extensions are different from Visual Studio. The can't be compatible with each other.

**Comment by aaron-bond** [comment]
@omsharp I used your extension not long after I had the notion for making this one and it really gave me the push to get this one finished at the time. Thanks for making something excellent!

@heartacker it's possible to set a user configuration for which comment delimiters you'd like to highlight, so you could change your own config to match @omsharp's extension. I can't change the defaults at this point cos it would break too many people's environments

**Comment by omsharp** [comment]
@aaron-bond 
Glad to hear that. :)

**Comment by heartacker** [comment]
> @omsharp I used your extension not long after I had the notion for making this one and it really gave me the push to get this one finished at the time. Thanks for making something excellent!
> 
> @heartacker it's possible to set a user configuration for which comment delimiters you'd like to highlight, so you could change your own config to match @omsharp's extension. I can't change the defaults at this point cos it would break too many people's environments

ok, thx all @omsharp @aaron-bond 👯
