### ISSUE TITLE
Feature idea - Comments as Footnotes

### ISSUE THREAD

**Issue by jeremy-farrance** [aaron-bond/better-comments#221]
Saw this and thought it would be an awesome feature to add to your already amazing extension.
https://twitter.com/justinmduke/status/1244042301225070592

Just seeing that mockup (below) is VERY compelling. In a nutshell, the ability to properly collapse and hide comments would be fantastic. Once hidden, give them some visibility and the easy option to view with a simple hover or click. Also probably needs an easy way to toggle the collapse/expand for all of them. Maybe also allow an option to pin one or more comments open?
 
You can read a tiny bit more about it here.
https://css-tricks.com/newsletter/192-animating-gradients-emoji-favicons-and-the-art-of-code-comments/

![image](https://user-images.githubusercontent.com/653301/77974771-c2c07680-72bd-11ea-9869-e6460205f342.png)

**Comment by aaron-bond** [comment]
This is an interesting idea but if anything it looks more like a mechanism to call out to some internal documentation. I'd sooner implement a totally new extension which allows you to "peek" urls in a comment and you could point to whatever you want. That's actually a really neat idea.

I also appreciate someone advocating on behalf of better comments (™ :p) in general, but I'd argue that hiding them away is anti-pattern.

Still, food for thought, so thanks :)
