### ISSUE TITLE
[Feature request] Ignore "#!/" on the first line

### ISSUE THREAD

**Issue by guojize** [aaron-bond/better-comments#227]
A line start with "#!/" is often a shebang line (I does not think an alert will start with "/"), so I think it shuold not be decorated.

I have read issue [#61](https://github.com/aaron-bond/better-comments/issues/61), but there are many interpreters other than python, such as bash, lua, tcl, etc.

Do you think this is an considerable option? @aaron-bond

**Comment by aaron-bond** [comment]
Rather than make this user-configurable I think I'll just fix on a case-by-case basis. For your needs here, what language should the first line be ignored?

**Comment by aaron-bond** [comment]
If I'm being honest - there are a lot of bugs raised specifically about the fact that in Python the extension ignores the first line and that's a right pain in the arse. Gonna close this until someone requests it for a specific language

**Comment by eevmanu** [comment]
For any language with which you can create a program / script which needs an interpreter to execute, would be really useful to ignore first line as comment like [Python](https://www.google.com/search?q=python+shebang), [Bash](https://www.google.com/search?q=bash+shebang) (even [Go](https://www.google.com/search?q=go+shebang)) and other ones.
