### ISSUE TITLE
python vs-code not functioning well 

### ISSUE THREAD

**Issue by TheFoxDecoder** [aaron-bond/better-comments#229]
![Screenshot 2020-04-15 at 07 26 53](https://user-images.githubusercontent.com/33922390/79290710-7ba3c980-7eea-11ea-8463-64c4272baa9a.png)

**Comment by aaron-bond** [comment]
Can you give me a bit more info here?

The sample in the project shows:  

![image](https://user-images.githubusercontent.com/14099631/80289150-bdc3db00-8734-11ea-8c33-71ea0849e8b3.png)

**Comment by aaron-bond** [comment]
Closing this since without more info I've nothing to go on
