### ISSUE TITLE
Rust's comments: not supported all variants

### ISSUE THREAD

**Issue by fzzr-** [aaron-bond/better-comments#23]
[Comments in Rust][] can start with various delimiters as described in the reference.

I don't know how yet, but [there](https://github.com/aaron-bond/better-comments/blob/master/src/parser.ts#L148-L151) should be regex or list with next options:

- `//` - Simple comment
- `///` - Outer line doc (exactly 3 slashes)
- `//!` - Inner line doc
- `/*!` - Inner line doc
- `/**` - Outer block doc (exactly) 2 asterisks

Firstly, please, disable `//!` for Rust because it's horrible when standard docs looks like attention like XXX or FIXME.

![screen shot 2018-01-10 at 00 12 20](https://user-images.githubusercontent.com/888526/34743530-112c8d56-f59b-11e7-938a-3f7dab69acd2.png)

[Comments in Rust]:https://doc.rust-lang.org/reference/comments.html

**Comment by aaron-bond** [comment]
hmmm... this one could be tricky. The delimiter for comments is currently set in one place for the language - there's no structure really for having multiple comment types supported.

Would it be reasonable to expect a user to change the default character for the attention comment coloring? You could update it in your settings to not work with ! and instead some other preference?

**Comment by aaron-bond** [comment]
Since this can be rectified by changing the OOTB configuration on the user-side, I think we can count this as working as expected. Unfortunately, there will always be some conflicts between languages

**Comment by tguichaoua** [comment]
A possible and elegant solution is to define the tag with a leading space.
You can still use `!` for important comment without disturbing rust doc.

```json
    {
      "tag": " !",
      "color": "#FF2D00",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": false,
      "italic": false
    },
```

![image](https://user-images.githubusercontent.com/33934311/188854136-d3f3853c-478f-4f87-acef-aaefaa9a4ea0.png)

**Comment by tguichaoua** [comment]
A possible and elegant solution is to define the tag with a leading space.
You can still use `!` for important comment without disturbing rust doc.

```json
    {
      "tag": " !",
      "color": "#FF2D00",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": false,
      "italic": false
    },
```

![image](https://user-images.githubusercontent.com/33934311/188854136-d3f3853c-478f-4f87-acef-aaefaa9a4ea0.png)
