### ISSUE TITLE
New tags: # and @

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [aaron-bond/better-comments#231]
Is it possible to add those new tags? 
\# an accent green and @ something like Purple or blue accent.

The color does not matter, the reason is, # would be good to define a title of a section of common codes, like common methods, and @ to simulate marking someone to check part of the code

**Comment by WilliamCunhaCardoso** [comment]
![Screenshot from 2020-04-26 13-45-18](https://user-images.githubusercontent.com/31575772/80313893-55243f00-87c4-11ea-87c6-4ae22211c872.png)

**Comment by WilliamCunhaCardoso** [comment]
this is the difference between \# and /*

![Screenshot from 2020-04-26 13-47-56](https://user-images.githubusercontent.com/31575772/80313924-8f8ddc00-87c4-11ea-9073-38b580cc5d21.png)

**Comment by brendan8c** [comment]
how to paste this code into settings.json??
It does not work for me

"better-comments.tags": [
  {
    "tag": "!",
    "color": "#FF2D00",
    "strikethrough": false,
    "backgroundColor": "transparent"
  }
]

**Comment by WilliamCunhaCardoso** [comment]
> how to paste this code into settings.json??
> It does not work for me
> I want to add my color comments
> 
> "better-comments.tags": [
> {
> "tag": "!",
> "color": "#FF2D00",
> "strikethrough": false,
> "backgroundColor": "transparent"
> }
> ]

Looks like ok. Make sure that you have added a coma on the statement before this one. And, you must close and open again the editor

**Comment by RubenVerg** [comment]
no need to close and reopen for me?
