### ISSUE TITLE
Color spans until end-of-line, not end-of-comment

### ISSUE THREAD

**Issue by BananaAcid** [aaron-bond/better-comments#233]
Simple example:

![image](https://user-images.githubusercontent.com/1894723/80502379-d8829380-8970-11ea-89fb-02f5d4020c2d.png)

In cases where there is
```css
{
/*! safari */ -webkit-whatever: unset;
/*! IE */ -ms-whatever: unset;
/*! FF */ -moz-whatever: unset;
}
```

... it kills all styling on the lines

**Comment by aaron-bond** [comment]
Tracking via https://github.com/aaron-bond/better-comments/issues/233
