### ISSUE TITLE
[Feature Request] Add list style ToDo along side X

### ISSUE THREAD

**Issue by Hamcker** [aaron-bond/better-comments#236]
For the Todo lists I offer to add a new microsyntax like this:

// TODO Create subsequent Person, RealPerson, Teacher and Student records
// [x] ~~Create Person~~
// [ ] Create RealPerson
// [ ] Create Teacher
// [ ] Create Student

then the `Create Person` item will be Strike-through and the other came just like TODO style or a bit different.

**Comment by aaron-bond** [comment]
You can add this to your own configuration in the settings. I actually think this is pretty cool, but it's not something I'd add to the defaults
