### ISSUE TITLE
Comments in the very first line are not colorized

### ISSUE THREAD

**Issue by paz10s** [aaron-bond/better-comments#238]
I use python and I found that comments, when using this extension, are not colorized on the first line.
Moving comments from first to second (or anywhere else) will bring back the color

**Comment by Bitnugger** [comment]
I use Nim and I have the problem too in the first line, but only with the: #?
Then an error is reported to me: **Error: invalid filter: <comment text>**

**@param myParam The ...** as can be seen in the details of this extension, does not work either.

**Comment by mrvkino** [comment]
Could it be related to #205 trying to disable colouring on the first line of script file?
