### ISSUE TITLE
Can't locate settings file for Visual Studio

### ISSUE THREAD

**Issue by dtsob75** [aaron-bond/better-comments#240]
I need to change the font colors, etc for some items that better comments uses.  All the docs say change the user or workspace settings.  However, I can't find where those settings are or how to add the changes.  I have searched my pc and can't find anything with the "better-comments" tags.

**Comment by MadaShindeInai** [comment]
> I need to change the font colors, etc for some items that better comments uses. All the docs say change the user or workspace settings. However, I can't find where those settings are or how to add the changes. I have searched my pc and can't find anything with the "better-comments" tags.

You should add fields you need to the settings.json Code>Preferences>settings> and find here a link to the settings json, or 'file from the Command Palette (Ctrl+Shift+P) with the Preferences: Open Keyboard Shortcuts (JSON) command.'
But if you mean Visual Studio instead Visual Studio Code - my answer will be useless for you)

**Comment by dtsob75** [comment]
Thanks for the reply, but I am indeed using Visual Studio 2019, not vs code.

**Comment by aaron-bond** [comment]
This extension doesn't work on VS2019. Perhaps you could try the brilliant extension by @omsharp: https://marketplace.visualstudio.com/items?itemName=OmarRwemi.BetterComments

https://github.com/omsharp/BetterComments
