### ISSUE TITLE
Feature Request: Allow Tabs on single line comments too

### ISSUE THREAD

**Issue by bekorn** [aaron-bond/better-comments#25]
I commonly put a tab after my comment delimiter and surprised this is not supported.

https://github.com/aaron-bond/better-comments/blob/f72ee08588c459fc50c47b45e6b06540693503f5/src/parser.ts#L35

Is there any problem if there would be a tab between the delimiter and the comment?

**Comment by aaron-bond** [comment]
Nope, this is totally doable. Just an oversight. I'll get something in there for you by this weekend :)

**Comment by bekorn** [comment]
Thanks 😄  Actually I think I can do it and pr if you want. As I understand the only change required is in this regex's second group:
https://github.com/aaron-bond/better-comments/blob/f72ee08588c459fc50c47b45e6b06540693503f5/src/parser.ts#L36

**Comment by aaron-bond** [comment]
Yeah you're exactly right about the regex. That's what I'd change too. Feel free to set up a PR if you have time :)
