### ISSUE TITLE
Request: Show comment colors on the minimap

### ISSUE THREAD

**Issue by RATIU5** [aaron-bond/better-comments#289]
I enjoy using Better Comments, however, I cannot see the colors on the minimap. When I have a long code file, it's difficult to scroll down and look for all the `TODO`s and `?`s. They appear gray on the minimap. Or, you could show the colors on the scrollbar. One example of this is by the Color Manager addon, v0.6.1. Either way, that will make Better Comments many times better.

**Comment by myahl-uncomn** [comment]
I understand that this issue was created before #312, but that issue has more activity. You might consider mentioning the Color Manager add-on there and closing this in favor of #312.
