### ISSUE TITLE
how can i use?

### ISSUE THREAD

**Issue by KingJeason** [aaron-bond/better-comments#30]
![image](https://user-images.githubusercontent.com/15926513/35351384-b2f481ca-017b-11e8-9547-d2d6d363a300.png)

**Comment by aaron-bond** [comment]
I think you'll need to close the comment block and it should work fine

**Comment by KingJeason** [comment]
why it doesn't auto close comment block?

**Comment by aaron-bond** [comment]
The plug in doesn't do that... Although VSCode usually does.

Try adding the `*/` manually

**Comment by aaron-bond** [comment]
JSDoc standard comments look like this:
![screenshot_20180124-191534](https://user-images.githubusercontent.com/14099631/35352223-2e886036-013b-11e8-901a-3f8a78f13800.jpg)

**Comment by KingJeason** [comment]
![image](https://user-images.githubusercontent.com/15926513/35352377-b1be3532-017e-11e8-872e-9cf7a5b88deb.png)

**Comment by KingJeason** [comment]
oh ,my,god, haha

**Comment by aaron-bond** [comment]
Is there a leak in your VSCode instance? That's a lot of CPU time!

**Comment by KingJeason** [comment]
i reinstalled  vscode  in 100 time in hours 
but 100%cpu!
i'm so sad

**Comment by KingJeason** [comment]
![image](https://user-images.githubusercontent.com/15926513/35352623-7d4fea38-017f-11e8-941b-f59e9bea808f.png)

**Comment by aaron-bond** [comment]
I will take a look at this soon. What language type is the file?

**Comment by KingJeason** [comment]
scss,but it is empty file

**Comment by KingJeason** [comment]
![image](https://user-images.githubusercontent.com/15926513/35352767-f5b81bf8-017f-11e8-95ea-c0ece937033c.png)
js is not go

**Comment by KingJeason** [comment]
![image](https://user-images.githubusercontent.com/15926513/35352852-40c65dee-0180-11e8-927a-6f281c22c383.png)
Did you use magic? Why all of a sudden?

**Comment by aaron-bond** [comment]
Thanks for the info. Can you confirm you're using version 1.1.8 of better-comments ?

**Comment by aaron-bond** [comment]
Ah! It might be the extra space between `!` and the comment?

**Comment by KingJeason** [comment]
![image](https://user-images.githubusercontent.com/15926513/35353001-bec78ff6-0180-11e8-8083-58b5713010d0.png)

**Comment by aaron-bond** [comment]
Ok in that case I'm very confused. Are you using a multi root workspace by any chance?

**Comment by aaron-bond** [comment]
Wow that's not good. I'll check with scss and is tonight to confirm there's no memory leak. Do you have other plugins running?

**Comment by KingJeason** [comment]
can you Remote assistance me ?

**Comment by aaron-bond** [comment]
No I can't do that (it's probably unwise to invite people on the web to access your machine...), but I will look into your issue from here

**Comment by KingJeason** [comment]
i belive you.because ilove you,love this plu

**Comment by KingJeason** [comment]
![image](https://user-images.githubusercontent.com/15926513/35353488-506821f4-0182-11e8-9c75-8cdb500b46b1.png)

**Comment by KingJeason** [comment]
Forget it,I guess that's the case with me only one. Forget me

**Comment by aaron-bond** [comment]
I think it's worth looking at just to check for an issue. I will add an update here when I know more

**Comment by KingJeason** [comment]
![image](https://user-images.githubusercontent.com/15926513/35354221-59107e44-0184-11e8-9ef0-beb9bdf45f4f.png)
Which is the right kind of writing.

**Comment by aaron-bond** [comment]
All is correct - the code expects the `TODO` to be followed by a comment. That's a bug

**Comment by KingJeason** [comment]
i using a multi root workspace by any chance

**Comment by aaron-bond** [comment]
Closing this off unless more info is provided
