### ISSUE TITLE
Need More Documentation

### ISSUE THREAD

**Issue by ChrisDev8** [aaron-bond/better-comments#316]
I have no idea on how to use it, all the tutorials are in Hindi. Please I need help. You have NO documentation on how to USE IT. the most important part of documentation IS NOT THERE.

**Comment by aaron-bond** [comment]
Have you looked at the README? It should be simple to follow

**Comment by aaron-bond** [comment]
@ChrisDev8 without any feedback I'm going to close this shortly.
