### ISSUE TITLE
Don't put default values in settings.json

### ISSUE THREAD

**Issue by wesbos** [aaron-bond/better-comments#327]
I just wanted to add 1 new tag type, and it seems I have to put all the default settings in there as well, which is a lot.

Could we just merge the custom settins overtop the defaults? So if we don't touch them, they stay the same as the default? Would make my settings.json much smaller.

**Comment by aaron-bond** [comment]
It would, but it would also make it harder for people to remove existing styles. Also, at this point I'd need a decent migration strategy if going down this route, and I don't think there's enough appetite for that just yet

**Comment by wesbos** [comment]
AHh yes I see, because it's an array. I was thinking just set it to null. 

Makes sense

**Comment by aaron-bond** [comment]
Your way would definitely be more user friendly. Dunno how to get from where it is now to there though

**Comment by leoshusar** [comment]
I was also looking for this. What about adding a new key? Something like
```json
"better-comments.custom-tags": [
    ...
]
```
This would keep the `tags` key functionality as it it now and `custom-tags` (or `additional-tags` or `new-tags` or whatever) would be merged with the default `tags` key.
