### ISSUE TITLE
PowerShell <#  #> comments are not highlighting multiline

### ISSUE THREAD

**Issue by R41z0r** [aaron-bond/better-comments#350]
In PowerShell Multiline highlighting isn't working:
![image](https://user-images.githubusercontent.com/6240199/131953967-5586921c-7add-41de-a8fa-ecd0a4a0b82f.png)
Should all be in same color of 'TODO'
`  {
            "tag": "todo",
            "color": "#FF8C00",
            "strikethrough": false,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
        }
`
Am I doing anything wrong?

**Comment by aaron-bond** [comment]
This isn't how the block comment highlight works.

See this example instead:
![image](https://user-images.githubusercontent.com/14099631/136112857-d3675aff-2954-441c-8525-9da681410b7a.png)
