### ISSUE TITLE
❤️Github Sponsors

### ISSUE THREAD

**Issue by thejustinwalsh** [aaron-bond/better-comments#353]
Add GitHub sponsor support so you can make some spare change off all of your hard work.

**Comment by aaron-bond** [comment]
I'm a bit out of the loop - care to explain what it is / how it works? A quick Google doesn't really leave me any the wiser. Is it an official GitHub thing?

**Comment by thejustinwalsh** [comment]
Yeah! Allows you to show a sponsor button on the project page and then GitHub users can sponsor your project with their billing account bound to their GitHub profile.

Try, https://github.com/sponsors/accounts, to see if you can sign-up. Not sure of the restrictions for your region, account, etc.

After setting it up, you can get lazy and just add a .gtihub repo so that sponsorship shows up on every project you host on GitHub too, if you so desire.

This is my setup -> https://github.com/thejustinwalsh/.github

**Comment by aaron-bond** [comment]
Many thanks for the info! I think I will set this up - it would certainly make it easier to justify spending some more time on this repo for sure.

**Comment by aaron-bond** [comment]
Thank you kindly for the advice here (and your sponsorship!).

I'm extremely grateful. Thanks :D
