### ISSUE TITLE
Please dont make //! alert for rust

### ISSUE THREAD

**Issue by bjorn3** [aaron-bond/better-comments#36]
Rust uses it for module documentation eg:

```rust
//! This library multiplies numbers

/*!
This is a multiline module doc comment
*/

fn mul(a: u8, b: u8) -> u8 { a * b }
```

**Comment by aaron-bond** [comment]
Duplicate of #23

Is it viable for you to change the config to use some other delimiter?

**Comment by bjorn3** [comment]
Yes, but I thought this extension could be changed to just disable it for rust sources only.

**Comment by aaron-bond** [comment]
As it's in the defaults, I don't think it makes sense to have such a specific change. My expectation would be that a user would customise the tags for their needs - in this case, removing / replacing the `!` in the configuration
