### ISSUE TITLE
Cannot add FIXME into default tags

### ISSUE THREAD

**Issue by h-e-n-r-y-t-a** [aaron-bond/better-comments#372]
#### I added FIXME to default tags in vscode setting, but no changes 
```json
"better-comments.tags": [
    {
      "tag": "!",
      "color": "#FF2D00",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": false,
      "italic": false
    },
    {
      "tag": "?",
      "color": "#3498DB",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": false,
      "italic": false
    },
    {
      "tag": "//",
      "color": "#474747",
      "strikethrough": true,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": false,
      "italic": false
    },
    {
      "tag": "todo",
      "color": "#FF8C00",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": false,
      "italic": false
    },
    {
      "tag": "fixme",
      "color": "#FF2D30",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": false,
      "italic": false
    },
    {
      "tag": "*",
      "color": "#98C379",
      "strikethrough": false,
      "underline": false,
      "backgroundColor": "transparent",
      "bold": false,
      "italic": false
    }
  ]
```
![Screenshot 2022-01-26 114431](https://user-images.githubusercontent.com/80365442/151235418-7145f73d-278a-4439-87e4-f848514beaeb.png)

**Comment by aaron-bond** [comment]
I'm not at my machine right now to verify, but I'm almost certain this is because of the `FIXME` in the source being all caps. The tags are case sensitive. Either make the config uppercase, or your comment lowercase; then it should be fine.

**Comment by h-e-n-r-y-t-a** [comment]
I tried to implement all caps or any possible cases or even change name tags to something else "@", "#", "xxx", ... no luck so far. Probably need to dive deeper into source code rather than only changes in vscode setting. Thanks for your quick reply though.

**Comment by h-e-n-r-y-t-a** [comment]
After restarting VSCode, FIXME and other updates showed up. This issue can be closed now.
