### ISSUE TITLE
Add support for Solidity

### ISSUE THREAD

**Issue by brucejayasinghe** [aaron-bond/better-comments#374]
Hi, 

I use comments when I'm auditing smart contracts, I just wanted to see if it would be possible to add support for Solidity? If so it would be incredibly helpful. I can't imagine it would be too difficult? Solidity uses `// /* */` comments.

Cheers

**Comment by vpavlin** [comment]
+1 for this request:)

**Comment by aaron-bond** [comment]
This is now supported in v3

**Comment by ddnexus** [comment]
I have v3 installed and it does not work with solidity. What did I miss?
