### ISSUE TITLE
Not working | Elixir | moduledoc

### ISSUE THREAD

**Issue by Ajwah** [aaron-bond/better-comments#38]
The issue pertains to `@moduledoc` in `Elixir`. 
```
@moduledoc """"
Some description
    !This does not work
"""
```
A normal comment `#! some comment` works fine.
I can also get `moduledoc` to be working if inside the triple quotes I add a `#` comment symbol with a tag:

```
@moduledoc """"
Some description
    # !This does work but now I will have to go through 500 files and adjust accordingly.
"""
```

Is it plausible to add support for tags to be working within `moduledoc`?

**Comment by aaron-bond** [comment]
I've had a few requests for different types of multiline support but haven't implemented anything for it yet:
https://github.com/aaron-bond/better-comments/issues/14
