### ISSUE TITLE
No dimmed colors for special characters

### ISSUE THREAD

**Issue by arsdever** [aaron-bond/better-comments#382]
When using special character visualizer feature of VS code, you get a result like this:
<img width="106" alt="Screen Shot 2022-03-16 at 12 24 58" src="https://user-images.githubusercontent.com/22396275/158547676-3362604a-4144-4059-b245-f4ba0761ca17.png">
where, as you see, the special characters (the spaces) have a bit darker colors, so they don't directly fall into your eye.

With the nice extension you created, however, the special characters have the same color as the rest of the comment:
<img width="92" alt="Screen Shot 2022-03-16 at 12 26 47" src="https://user-images.githubusercontent.com/22396275/158547906-7c92fc23-144f-4b95-bc7e-d5a8490873bf.png">

which makes it much more difficult to read, especially when there are a lot of spaces (special characters). 

It'd be a lot convenient to have these characters dimmed out as well.

**Comment by arsdever** [comment]
I just noticed, that on the windows platform, things are a bit different. When my cursor is at a line containing `better-comments`, the colors of the special characters are not dimmed. Otherwise, the color of special characters is the default color as per vscode.

### When on line
![on_line](https://user-images.githubusercontent.com/22396275/160249695-6ea3e716-c650-4cd5-8a17-38890038b331.png)
### When out line
![out_line](https://user-images.githubusercontent.com/22396275/160249697-f9371cf6-fbde-41b4-803e-94db1dfa61d0.png)

I'll investigate the behavior on mac and give updates.

**Comment by Heikrana** [comment]
Possible duplicate #7
