### ISSUE TITLE
Can't find where I can change or add tags.

### ISSUE THREAD

**Issue by hggc5x** [aaron-bond/better-comments#384]
I can't find the place where I could change the color of different tags  or add new tags with new colors.

(I found settings.json, but the tags are not there.)

**Comment by Heikrana** [comment]
You can add the settings yourself, like this
```JSON
"better-comments.tags": [
  {
    "tag": "!",
    "color": "#FF0000",
    "strikethrough": false,
    "underline": false,
    "backgroundColor": "transparent",
    "bold": false,
    "italic": false
  },
]
```

**Comment by hggc5x** [comment]
Thanks for the answer, I just realized I pasted it wrongly, so it just works fine.
