### ISSUE TITLE
If comment start with first line and first column highlight don`t work

### ISSUE THREAD

**Issue by DaSh-More** [aaron-bond/better-comments#399]
It is not work
![30-04-2022_213612_Code](https://user-images.githubusercontent.com/52647986/166118327-ceb58dfb-b828-4d2e-b1a2-e9b0b3fc230b.png)
but it is work
![30-04-2022_213624_Code](https://user-images.githubusercontent.com/52647986/166118333-e6bc9d96-fff7-4e87-a0bb-cc3342e5be0b.png)

**Comment by almazgaliev** [comment]
see #61
