### ISSUE TITLE
No highlighting in Vue 3 components

### ISSUE THREAD

**Issue by default-kaas** [aaron-bond/better-comments#402]
In the Vue 3, the comment highlights do not seem te work.
As seen here:
![image](https://user-images.githubusercontent.com/23498867/169242540-5adddbc7-caba-40b1-9727-07dcb0bd0cc9.png)

Mean while in my typscript files it does work.
![image](https://user-images.githubusercontent.com/23498867/169242632-bec36a20-b821-40ec-993e-2a246647f949.png)

In the overview of the extention vue.js is listed as supported.
![image](https://user-images.githubusercontent.com/23498867/169242816-4d8e8d04-0e33-4310-b014-0dc70f742a43.png)

Does anybody know how to fix this issue?

**Comment by Tenrys** [comment]
https://github.com/aaron-bond/better-comments/issues/388#issuecomment-1122378337
