### ISSUE TITLE
JSX/TSX single-line comments

### ISSUE THREAD

**Issue by Netail** [aaron-bond/better-comments#403]
Would love to see this supported:
![image](https://user-images.githubusercontent.com/11695769/170223120-53fd80f0-d209-4c0d-9da1-ac1d1ba28473.png)

**Comment by wolfmcr** [comment]
any possibility of this in the near future?

**Comment by edwinhuish** [comment]
@Wolfgang-stack Does this solved the problem?  [Better Comments (with embedded languages support)](https://marketplace.visualstudio.com/items?itemName=EdwinHuiSH.better-comments-next)

**Comment by wolfmcr** [comment]
@edwinhuish yes, yes it does THANK YOU

**Comment by Netail** [comment]
Closing this issue as this repo is not worked on anymore, moved to Edwinhuish's fork
