### ISSUE TITLE
Language support: Object Pascal

### ISSUE THREAD

**Issue by pakLebah** [aaron-bond/better-comments#41]
Please, add support for object [pascal](http://freepascal.org) (modern [pascal](https://www.embarcadero.com/products/delphi)) programming language.

The [comment](http://wiki.freepascal.org/Comments) syntaxes in object pascal are:
- line comment: `//`
- block comment:
    - `{`…`}`
    - `(*`…`*)`

~Can you just add an option to make this extension works on *any* kinds of file? By simply using the given tags. So everyone could use this extension on any languages that haven't yet supported, while waiting for official support.~

Thank you.

**Comment by aaron-bond** [comment]
Thanks for the suggestion. I'll get the single line support in this weekend.

The reason I've set it up to pick up different file types is that someone might have multiple files in their workspace using different languages, but expect them all to have their comments picked up. The parser uses the language type to pick up the comment format.

It might be a bit before I drop in support for multiple types of multiline comment though. JSDoc are the main multiline comments that are supported atm, and supporting more requires a bit of a rework.

**Comment by pakLebah** [comment]
Actually, I didn't mean you should support multiple languages in a single file. What I meant is you should support any languages that hasn't yet officially supported. Something like a general comment mark that works on any kind of languages.

For example, when a user open a pascal file (`.pas`) which hasn't yet supported, then your extension treat every single `//` as a line comment. The `//` mark is user customizable through setting. So, while pascal file hasn't yet supported officially, your users are still able to use your extension.

But, support for multiple languages in a single file would be great though. 😊

**Comment by pakLebah** [comment]
I apologize I didn't make myself clear about this. I shouldn't have mixed two requests in a single issue report. This issue is supposed to be only about pascal file support request. The custom comment mark should be discussed in my other issue report. I'll remove the second request from this issue.

**Comment by aaron-bond** [comment]
What's the extension for modern pascal? I've found lpr but there's no built-in language support for it that I can see?

**Comment by pakLebah** [comment]
It's `.pas` or `.pp` for source code files and `.lpr` or `.dpr` for project files.

**Comment by pakLebah** [comment]
Oh, did you mean vs extension? It's [omnipascal](https://marketplace.visualstudio.com/items?itemName=Wosi.omnipascal).

**Comment by aaron-bond** [comment]
Thanks, I needed omnipascal before I could detect the language :)
