### ISSUE TITLE
Consider becoming a verified publisher

### ISSUE THREAD

**Issue by isidorn** [aaron-bond/better-comments#410]
VS Code PM here again,

Consider becoming a verified publisher. More details about this here https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

We would love this to happen, so let us know if we can help from our side. Thank you

fyi @chgill-MSFT

**Comment by aaron-bond** [comment]
Hi @isidorn, I'd really like to do this but as far as I can tell this requires some form of web-hosting? I own an appropriate domain (it redirects to my github.io page), but without the hosting to go with it I can't add any SSL certs. Any recommendations to avoid the cost of hosting just for the purposes of verification?

**Comment by isidorn** [comment]
Thanks for sharing the details
@chgill-MSFT might have an idea on what is the best path forward here, since I know he has been thinking about this.

**Comment by Lomby21** [comment]
Hi @aaron-bond, I believe the cloudflare free tier includes SSL certs if that might be an option for you?

**Comment by aaron-bond** [comment]
Hi @Lomby21, CloudFlare was exactly what I needed. I didn't realise they offered hosting, so thanks for the tip!

@isidorn I've gone through the process and applied for verification. Thanks for the help 👍
