### ISSUE TITLE
Feature request: comment mark as settings

### ISSUE THREAD

**Issue by pakLebah** [aaron-bond/better-comments#42]
Could you please add some settings to let us define custom comment marks? My proposal is:

- add a section to define block comment syntax,  for example:  
  `"block comment": {`  
    `  "start mark": "(*"`  
    `  "stop mark": "*)"`  
  `}`
- add an option to define (single) line comment syntax, for example:  
  `"line comment mark": "//"`
- add an option to toggle this custom comment feature, for example:  
  `"custom comment": true`

These custom comment marks settings would only work if the language isn't recognized by the extension. Otherwise the extension would use the official language comment syntax. This way would enable user to use this extension for any kinds of programming languages that haven't yet supported, until they are supported officially.

Thank you.

**Comment by aaron-bond** [comment]
usually the turnaround on adding a language into the parser is a few days from being requested. I've been a bit lax on updates this month so there's a few waiting to go in, but for the most part there's not much wait.

Having the extension activate on ANY file would probably be OK, but I like that the control is there to turn it on when I'm sure the parser can support the language. I have a set of test files locally for these languages that I check against to make sure it's all good to go.

Still though, I can see the benefit of this. I'll consider ways to make it work. Feel free to give any suggestions if you have ideas for the code changes :)

**Comment by pakLebah** [comment]
Most of us usually use one language at a time. The benefit of this feature is obvious. This custom comment mark setting would supports virtually any kind of programming languages available out there that haven't yet supported by the extension. Though it's not an ideal solution, but it should work.

**Comment by pakLebah** [comment]
A little additional detail to this proposed feature… when this custom comment mark is activated, you should treat all `'` **and** `"` as string mark (like HTML string). So when your extension sees a line like this:

`writeln('this (* is inside a string');`

it doesn't make it into this:

`writeln('this `_(* is inside a string");_

**Comment by aaron-bond** [comment]
"Most of us usually use one language at a time"

I don't know that that's true. VSCode has a huge number of people working on web sites / applications where they're writing in HTML, JS, TS, CSS, SCSS/LESS at the same time...

**Comment by aaron-bond** [comment]
One thing to note on this - I'm working on a proposal to support text files as part of: https://github.com/aaron-bond/better-comments/issues/39
When a language that isn't detected by VSCode comes through the parser, it's detected as plaintext - so this might alleviate some of your need

**Comment by aaron-bond** [comment]
Closing this as I've (finally) implemented block comments support. If you have a language in mind you'd like support for, please raise a feature request. Thanks!
