### ISSUE TITLE
Tags for comments ?

### ISSUE THREAD

**Issue by SheepDomination** [aaron-bond/better-comments#43]
I was hoping tags for comments could be added;  though the command palette you could search the tag for the severity of the comment.  For example one comment would have a tag of; maybe.  When searching for tags if there is more then one comment with the tag of, maybe you can quickly view them ?

**Comment by aaron-bond** [comment]
I've wanted to do something like this for a while with the TODO tags but it makes sense to do them all. I'll give this one another look :)

**Comment by SheepDomination** [comment]
It would be appreciated; also utilize Visual Studio Code Icons such as the light-bulb icon for tags such for _ideas_.

**Comment by aaron-bond** [comment]
Interesting... Would Unicode characters /emojis work in code files?

Might try that out

**Comment by SheepDomination** [comment]
Not sure if Unicode characters / emojis work in code files but then again they appear when you have a warning within Visual Studio Code, it would be shocking if you couldn't use icons within code files and have them save as Unicode characters.  Each category annotation could have an icon.

**Comment by SheepDomination** [comment]
Any update ?
