### ISSUE TITLE
What does this property do?

### ISSUE THREAD

**Issue by BrunoUY** [aaron-bond/better-comments#433]
"backgroundColor": "transparent",

And how to change it?

thank you

**Comment by aaron-bond** [comment]
This will just add a background to the highlighted comment. 
If I change it on mine:
![image](https://user-images.githubusercontent.com/14099631/196037337-24156fa9-60c1-41d4-8235-a4ebd55805da.png)

then the result is:
![image](https://user-images.githubusercontent.com/14099631/196037360-9c094f52-4134-456d-809d-e88ae6956fd0.png)

Just use any hex value for the colour.
