### ISSUE TITLE
C and C++ highligting

### ISSUE THREAD

**Issue by SanjayVyas** [aaron-bond/better-comments#437]
All of a sudden, C and C++ are no longer highlighting comments. Has anything changed recently?

**Comment by Xelbayria** [comment]
I had the same problem. It has to do with the new version of VSCode: 1.72.0. 
i'm going back to the previous version where it's working properly until this issue is sorted out.

**Comment by zxl19** [comment]
Hi @aaron-bond , thank you for your excellent work. I also encountered the same problem as described above. The most recent operation I did was upgrading my VS Code to 1.72.0. I wonder if this could be relevant to this issue.

Best regards.

**Comment by krayfaus** [comment]
Thanks @Xelbayria, just did the same.

I'll leave some instructions here to anyone upset with this issue.
You may find older installers on the official website <https://code.visualstudio.com/updates/v1_7>.
And if you add "update.mode": "none" to your "settings.json" you stop Code from updating itself.

**Comment by krayfaus** [comment]
Thanks @Xelbayria, just did the same.

I'll leave some instructions here to anyone upset with this issue.
You may find older installers on the official website <https://code.visualstudio.com/updates/v1_71>.
And if you add "update.mode": "none" to your "settings.json" you stop Code from updating itself.

**Comment by sterben-01** [comment]
same issue

**Comment by ZanzyTHEbar** [comment]
Same issue. Love this extension - hope that this get's resolved switfly.

**Comment by lux-ok** [comment]
Same issue after update to vscode1.72.0. 
My code's comment are pitch black now >.<
Better-comment is my favorite extension, waiting for fixed version anxiously.
Thanks to contributors.

**Comment by jerry762** [comment]
I've got the same issue with vscode v1.72.0.

**Comment by CODE-FOR** [comment]
same issue

**Comment by roboterl** [comment]
same problem for 1.72.0

**Comment by Xelbayria** [comment]
> My code's comment are pitch black now >.<

if you want to change the colour of your comment, I have the solution for that. it is temporary until the issue is fixed. 
You can put it in your settings.json
```json
"editor.tokenColorCustomizations": {
	"comments": "#ffffff" // pick any color
},
```
OR 
you can "down-date" to v1.71.2 and await for the issue to be fixed.

**Comment by idma88** [comment]
Investigation revealed that the problem was in the file `Microsoft VS Code\resources\app\extensions\cpp\language-configuration.json` which was missing a comma at the end of line 16.
This caused the JSON parser to throw an error and flag `cpp` as an unsupported language.
The corresponding [PR](https://github.com/microsoft/vscode/pull/163182) has already been submitted to the VS Code repository.
Waiting for update...

**Comment by aaron-bond** [comment]
Many thanks for the investigation @idma88, much appreciated!

**Comment by Xelbayria** [comment]
> Investigation revealed that the problem was in the file `Microsoft VS Code\resources\app\extensions\cpp\language-configuration.json` which was missing a comma at the end of line 16. This caused the JSON parser to throw an error and flag `cpp` as an unsupported language. The corresponding [PR](https://github.com/microsoft/vscode/pull/163182) has already been submitted to the VS Code repository. Waiting for update...

Can confirm the VSCode's `language-configuration.json` is missing the comma at the end of line 16. i just simply add a comma at the end of line 16 and now it's working 👍 Well done. that's a good lesson for me

**Comment by thomaschoi721** [comment]
> 調查顯示問題`Microsoft VS Code\resources\app\extensions\cpp\language-configuration.json`出在第 16 行末尾缺少逗號的文件中。 這導致 JSON 解析器拋出錯誤並標記`cpp`為不受支持的語言。 對應的[PR](https://github.com/microsoft/vscode/pull/163182)已經提交到 VS Code 倉庫。 等待更新...

**Comment by thomaschoi721** [comment]
> 調查問題`Microsoft VS Code\resources\app\extensions\cpp\language-configuration.json`16 行已經顯示出在第一個公開的文件中。 這導致 JSON 解析器拋出錯誤並標記`cpp`為不受支持的語言。 公關[和](https://github.com/microsoft/vscode/pull/163182)代碼。 等待更新...

Thank you very much for your contribution！

**Comment by lux-ok** [comment]
> Investigation revealed that the problem was in the file `Microsoft VS Code\resources\app\extensions\cpp\language-configuration.json` which was missing a comma at the end of line 16. This caused the JSON parser to throw an error and flag `cpp` as an unsupported language. The corresponding [PR](https://github.com/microsoft/vscode/pull/163182) has already been submitted to the VS Code repository. Waiting for update...

Thank you very much for your contribution, according to your operation, I have regained the “better-comments" function.

**Comment by atsju** [comment]
Indeed, you can add a `,` yourself at line 16 in file `C:\Users\XXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\cpp\language-configuration.json`

Thank you

**Comment by aaron-bond** [comment]
They've fixed the issue and it's in preview, and should release soon: https://github.com/microsoft/vscode/issues/163181

**Comment by egmnklc** [comment]
> Investigation revealed that the problem was in the file `Microsoft VS Code\resources\app\extensions\cpp\language-configuration.json` which was missing a comma at the end of line 16. This caused the JSON parser to throw an error and flag `cpp` as an unsupported language. The corresponding [PR](https://github.com/microsoft/vscode/pull/163182) has already been submitted to the VS Code repository. Waiting for update...

That solved my issue, thanks!

**Comment by ahmadasmandar** [comment]
> Investigation revealed that the problem was in the file `Microsoft VS Code\resources\app\extensions\cpp\language-configuration.json` which was missing a comma at the end of line 16. This caused the JSON parser to throw an error and flag `cpp` as an unsupported language. The corresponding [PR](https://github.com/microsoft/vscode/pull/163182) has already been submitted to the VS Code repository. Waiting for update...

Thank you very much, it fixed my problem.
