### ISSUE TITLE
Not working on my pc

### ISSUE THREAD

**Issue by Sumitrajak2002** [aaron-bond/better-comments#439]
Type: <b>Bug</b>

this extension not working on my pc but working on my friend's pc

Extension version: 3.0.2
VS Code version: Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:22:48.346Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800HS with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.42GB (6.39GB free)|
|Process Argv|--crash-reporter-id 5b4a5543-5858-48d9-85aa-5af626b255ee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30583748
fc301958:30573243

```

</details>

**Comment by abram-krislock** [comment]
This was working just fine until the latest VS Code update:

![image](https://user-images.githubusercontent.com/90422800/195369232-f8642aa5-7e0d-420a-883d-f4381daddd8b.png)

**Comment by yuxuan-z19** [comment]
same here

**Comment by StevenMacias** [comment]
Same here: 
- Extension version: 3.0.2
- VS Code version: Code 1.72.0
- OS: Arch Linux x86_64
- Kernel: 5.19.13-arch1-1

**Comment by aaron-bond** [comment]
This is an error in VSCode's own CPP language configuration. They've fixed the issue and it's in preview, and should release soon: https://github.com/microsoft/vscode/issues/163181
