### ISSUE TITLE
Better Comments Not Working In C++ Only After Last VsCode Update

### ISSUE THREAD

**Issue by mghalix** [aaron-bond/better-comments#440]
Type: <b>Bug</b>

Before the previous update it used to work perfectly, now it does not highlight my comments what so ever when i am working in a c++ project. Note it is working for other languages like java / python / c#.

Extension version: 3.0.2
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.15.0-50-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|7.51GB (2.15GB free)|
|Process Argv|--unity-launch --crash-reporter-id 35c94d52-0c9e-40b1-a019-0d4e196b6a95|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by olonsoft** [comment]
Same here!

**Comment by Fayxx** [comment]
Same here. Tried mixing arround the config and reinstalled but still no changes.

**Comment by olonsoft** [comment]
There is a bug in VSCode.
Look [here](https://github.com/aaron-bond/better-comments/issues/437#issuecomment-1274590408) for a solution.

**Comment by mghalix** [comment]
> There is a bug in VSCode. Look [here](https://github.com/aaron-bond/better-comments/issues/437#issuecomment-1274590408) for a solution.

I have tried it on my windows and it actually worked! though I can't seem to find the cpp language-configuration.json file on linux .vscode folder... any idea where is it located?

**Comment by Ronalyo** [comment]
found mine at ```/usr/share/code/resources/app/extensions/cpp/```
hope this helps

**Comment by aaron-bond** [comment]
This fix is now in insiders release of VSCode and will make its way into release shortly. Thanks for raising this with me.
