### ISSUE TITLE
bug: @param isn't working on pascal file

### ISSUE THREAD

**Issue by pakLebah** [aaron-bond/better-comments#45]
Just updated to the latest version of this extension, v.1.2.0. And I found some bugs.

The `@param` of jsdoc feature isn't working, at least with pascal source file. Screenshot attached, the bug is shown at the line number 18.

Screenshot:
![better-comments-report](https://user-images.githubusercontent.com/11470932/37629804-74306176-2c13-11e8-86cd-25a03f5a3eed.png)

**Comment by aaron-bond** [comment]
I think there's some confusion here... The JSDoc format of comments is only for .is and .ts files. Highlighting the @param is something VSCode does, not the extension.

In other languages where /* */ is the multiline comment format, the extension will work as expected, but you'll not find @param highlighting like in the others.

Also, if you use the multiline comments, there are two modes:
/* / -- each line within can start with your comment tag (, ?, etc.)
/** */ -- each line within must start with * and then your comment tag
