### ISSUE TITLE
bug: rendering failed after switching to unsupported file type

### ISSUE THREAD

**Issue by pakLebah** [aaron-bond/better-comments#47]
The extension fails to render comments correctly after switching to unsupported file types such as `.gitignore` file or a plain text file. Is this a known bug?

Bug evidence:
![licecap record at 13 02](https://user-images.githubusercontent.com/11470932/37638424-6909d8c8-2c3f-11e8-8fd7-da6bf38e9dfa.gif)

Workaroud:
Restart VS Code and **never** open any files that are not supported by this extension while you need to use this extension.

Info:
– extension v.1.2.0
– vscode v.1.21
– macOS v.10.11

**Comment by pakLebah** [comment]
The evidence also shows that `@param` mark is not rendered correctly as well.

**Comment by aaron-bond** [comment]
I think there's some confusion here... The JSDoc format of comments is only for .is and .ts files. Highlighting the @param is something VSCode does, not the extension.

In other languages where /* */ is the multiline comment format, the extension will work as expected, but you'll not find @param highlighting like in the others. 

Also, if you use the multiline comments, there are two modes:
/* */ -- each line within can start with your comment tag (*, ?, etc.)
/** */ -- each line within must start with * and then your comment tag

**Comment by aaron-bond** [comment]
Hmmm I thought I'd resolved this with the 1.2.0 release. Thanks for the repro steps. I'll take a look
