### ISSUE TITLE
Use ! ? as tags only if followed by white space

### ISSUE THREAD

**Issue by khanybaba** [aaron-bond/better-comments#480]
In JS the ! is the logical not operator
it is not uncommon to find a ternary statement of the form
`!variable ? execute_this : execute_that`
when commenting such a line of code Better Comments takes the initial exclamation mark to be a tag
requiring (or providing an optional setting that will require) a tag to be followed by whitespace will prevent these commented lines from being incorrectly tagged

**Comment by porg** [comment]
### Your desired customization is already possible now
1. Open Settings (`⌘ ,`  on a Mac)
2. Search for "Better Comments". Click on: Extensions →  Better Comments.
3. Tags:  [Edit in settings.json]()  👉 Click that link to open the settings file
   - Find the array `"better-comments.tags":` (currently on line 31)
   - Find `"tag": "!",` (currently on line 35) and change it to `"tag": "! ",` (space character after the exclamation mark)
4. Restart VSCode.

✅ From now on that style is only applied to comment lines starting with `! `.

Did that solve your issue? If so you may close the issue.
- Note I'm not the maintainer, just a fellow user who stumbled across your issue and volunteered with info.
- Hope it helped.

**Comment by khanybaba** [comment]
Thank you. Much appreciated!
