### ISSUE TITLE
Feature Request: @ to jump to a given position.

### ISSUE THREAD

**Issue by pakLebah** [aaron-bond/better-comments#49]
I'd like to propose a new feature. It's a common practice in coding that inside a comment we need to point a specific position in the source code to explain something. For example, this comment

`// the code block below is similar to a code block @123,5`

would render `@123,5` like a link (underlined). If it's clicked, the cursor will jump to line 123 column 5. If the column value is omitted, the default value is 1 (first column). It's like a shortcut for go to line command. Doing an undo (or go back?) would bring the cursor back into the previous location. 

It'd be great if it's able to jump into another file. For cross file jump, the syntax should be `filename.ext@line[,column]`. For example: `test.pas@10,5` would jump to `test.pas` file at line 10 column 5.

Is this kind of feature possible to be implemented? What do you think?

Thank you.

**Comment by aaron-bond** [comment]
Yeah that should be possible - all the current decorations are just modifiers on the text, so I don't see why it couldn't pick up a click event too.

One thing to note though is that line refs in code don't work too well since you add and remove lines all the time... more likely it would need to point to a method name or another comment...

**Comment by pakLebah** [comment]
Yes, lines are changing all the time. But it's not the extension's responsibility to update the comment, right?

Jump to a method name is usually provided by a language extension. It's great idea nevertheless. But how do you jump to another comment? A comment doesn't have an identifier.

**Comment by aaron-bond** [comment]
Yeah I don't have any great ideas for either of those. I'm working on an update to show TODO items in the explorer window at the minute but I'll have a look into this one after

**Comment by aaron-bond** [comment]
I haven't found any neat ways of doing this kind of in-file navigation in a way that I'd like, so for now I'm going to close this one off. The TODO task I'm working on is tracked separately
