### ISSUE TITLE
Feature request: Support for Svelte Files

### ISSUE THREAD

**Issue by SharkmanZA** [aaron-bond/better-comments#503]
Svelte is amazing and an up and coming framework. Would love to have this support svelte. Thanks again!

**Comment by SharkmanZA** [comment]
More specifically TODO comments in the script portion of the file

**Comment by dslatkin** [comment]
If you do an issue search for the word Svelte, you'll notice #174 is already opened.

There hasn't been any real movement on it, but you [can use this fork](https://github.com/aaron-bond/better-comments/issues/174#issuecomment-1688401754).
