### ISSUE TITLE
Add Typst language support

### ISSUE THREAD

**Issue by chillcicada** [aaron-bond/better-comments#508]
Hi @aaron-bond. Typst is a new markup-based typesetting system for the sciences (picked up from the [Tpyst official website](https://typst.app/docs/)).

Typst has three syntax modes:
- Markup
- Math mode
- Code mode (you can program in Typsta though it's a markup language.)

## Typst comments in Markup and Code Mode

In these modes, Typst can comment like C/C++. Below is an example:

```typ
// This is a one-line comment.
... // This is also a one-line comment.
/*
This is a block comment.
*/
```

For block comment syntax, the `/*` will precedently match the first `*/` no matter where the matched `*/` is unless it gets escaped by escape character `/`. Below is an example:

```typ
/* This is a block comment that contains a */ character. */
/*
This is a block comment that contains a */ character.
*/
```

Redundant `*/` will result in a render error (unexpected end of block comment).

Comments can also omit the whitespace and line break, like:

```typ
//This is a one-line comment.
... //This is also a one-line comment.
/*This is a block comment.*/
```

## Typst comments in Math mode:

Like many other markup languages (such as markdown). Typst also has inline math (`$ x^2 $`) and block-level math (`$ x^2 $`) two modes.

Most of the comment syntax in math mode is the same as the markup and code mode:

```typ
...$/* this is a comment in inline math */$...

$
// This is a one-line comment in block math.
... // This is also a one-line comment in block math.
/*
This is a block comment in block math.
*/
$
```

Well, the difference happens when using one-line comment in inline math.The below codes will throw a render error (unclosed delimiter):

```typ
...$ // This is a one-line comment in inline math. $...
```

It means that the one-line comment in inline math is not premitted.

---

That's all. Hopefully this feature will be added in the future version.

**Comment by edwinhuish** [comment]
Did you try [Better Comments (with embedded languages support)](https://marketplace.visualstudio.com/items?itemName=EdwinHuiSH.better-comments-next) ?

**Comment by chillcicada** [comment]
> Did you try [Better Comments (with embedded languages support)](https://marketplace.visualstudio.com/items?itemName=EdwinHuiSH.better-comments-next) ?

Thanks for ur advice, it works.

**Comment by chillcicada** [comment]
## I find that aaron-bond's better-comments extension can primarily support the comment highlight of Typst.

**It's my wrong format that resulted in the invalid rendering.** 😥
