### ISSUE TITLE
Language support: JSON with comment (jsonc) files

### ISSUE THREAD

**Issue by pakLebah** [aaron-bond/better-comments#51]
Please, add support for JSON with comment (jsonc) files.

Thank you.

**Comment by aaron-bond** [comment]
I can't find any references to that language (other than json-c), and VSCode doesn't detect the extension .jsonc. Where can I find some samples?

**Comment by pakLebah** [comment]
JSON-with-comments is practically a JSON file. The difference is VS Code will complain if a JSON file contains comments, except it's set as a JSON-with-comments file. Both use `.json` file extension. VS Code sets the language ID to simply `json` for normal JSON file and `jsonc` for JSON-with-comments file. Check out the language association selection below.

Language selection on VS Code:
![jepretan layar 2018-03-21 pada 17 57 00](https://user-images.githubusercontent.com/11470932/37706273-82533b92-2d31-11e8-92dd-dcb7b074c2eb.png)
