### ISSUE TITLE
How do i color comments to HTML ?

### ISSUE THREAD

**Issue by murugappanrm** [aaron-bond/better-comments#511]
This extensions shows only example for languages other than HTML. How do i color code the HTML Comments?

**Comment by edwinhuish** [comment]
Same.

```html
<!--
! comment one
# comment two
? comment three
-->
```

**Comment by murugappanrm** [comment]
Sorry Bro, does not seem to work.

![Screenshot_1](https://github.com/aaron-bond/better-comments/assets/63133893/d3f8032b-4897-4fc2-a7d4-7a5c19212e5d)

**Comment by edwinhuish** [comment]
Try this https://marketplace.visualstudio.com/items?itemName=EdwinHuiSH.better-comments-next

**Comment by murugappanrm** [comment]
@edwinhuish 

You must have fixed the problem in your version of the extension. It works great, thank you. One question. What does "better-comments.tagsDark" do?

Also if you could enhance what this one can do, it will make life complete: https://marketplace.visualstudio.com/items?itemName=ashhitch.vs-code-css-comments

**Comment by edwinhuish** [comment]
> What does "better-comments.tagsDark" do?

`better-comments.tags` is the default tags options.
`better-comments.tagsDark` will overwrite `better-comments.tags` when use dark theme.
`better-comments.tagsLight` will overwrite `better-comments.tags` when use light theme.



> Also if you could enhance what this one can do, it will make life complete: https://marketplace.visualstudio.com/items?itemName=ashhitch.vs-code-css-comments

I think this is not the "better comments" functional scope.

**Comment by murugappanrm** [comment]
Hi,
Thank you for the update. 

Does `better-comments.tagsLight` i have to create my own values and setting and it will apply when i set the theme for vscode to a light version?

With regards to the enhancements, its only my wish list as i feel that both are related to comments in codes. I understand if it cannot be done. Hopefully another extension comes along.

**Comment by edwinhuish** [comment]
> Does better-comments.tagsLight i have to create my own values and setting and it will apply when i set the theme for vscode to a light version?

YES

**Comment by murugappanrm** [comment]
Ah, I see thank you so much. We shall close this issue/discussion.
