### ISSUE TITLE
Markdown Not Support?

### ISSUE THREAD

**Issue by RocMark** [aaron-bond/better-comments#53]
I'm using this extension with markdown file for months ,
it works great!
but suddenly it didn't work!?
any idea?

**Comment by RocMark** [comment]
I using .vsix file Downgrading to 1.1.0 it works!

**Comment by aaron-bond** [comment]
Hey, this was probably changed by https://github.com/aaron-bond/better-comments/issues/47

The fix was to not break when showing unsupported types. The fact that markdown has been working is probably just a coincidence. 

Can you show me a sample of how you were using comments in Markdown? I didn't think they were supported...

**Comment by RocMark** [comment]
yup i think the unsupported types did'nt  add markdown in list , so it makes markdown don't work
My method is quite weird. Its like a hack , but I dont know how this is working LOL

**Comment by aaron-bond** [comment]
Your English is fine :)

I see from this thread that there is no real comment indicator on Markdown: https://stackoverflow.com/q/4823468/1749630

Perhaps I could add support for "[comment]: # ! Important comment" as mentioned there?

**Comment by RocMark** [comment]
yeah there is not comment indicator
i just use this extension for highlighting line when writing my own note
the output of the markdown file with //* will act like plain text
I think I'm the only one use this extension like this XD
thx for reply !!
I'm just a junior web developer really don't know how the extension works sorry about that

**Comment by aaron-bond** [comment]
I'll try adding support for the `[comment]: #` tag this weekend. I don't think I can add support for `//` because that's not a recognised comment format for the language, unfortunately. Are you able to update your code to use a different format for the comments?

**Comment by RocMark** [comment]
I'm using this for writing learning note that all
So i dont need it work on markdown output file

![testmd](https://user-images.githubusercontent.com/33424161/37835595-82868da6-2eeb-11e8-98e6-9000c4452f14.png)

**Comment by aaron-bond** [comment]
I'm going to close this as I haven't found a sensible way to support markdown since it has no actual comment syntax. Sorry. Feel free to contribute if you have any ideas how this could be done :)

**Comment by linhtto** [comment]
@aaron-bond , I think both of the ways mentioned here on how to comment in Markdown work. Maybe you can support both?

Way 1: `<!-- COMMENT GOES HERE -->`
Way 2: `[comment]: # "COMMENT GOES HERE"`

In fact, VSCode recognizes Way 1 as a default type of comment, and it even grays it out. Way 2 works too (i.e., it won't show up in the output), but it's not grayed out by VSCode.

**Comment by aaron-bond** [comment]
Closing as duplicated in #91
