### ISSUE TITLE
FYI --> Looks like this has been forked to "Better Comments Next"

### ISSUE THREAD

**Issue by jwoodard80** [aaron-bond/better-comments#546]
Came here looking to see updates and looks like the project has been abandoned. However, there appears to be a active fork at the "Better Comments Next" repo. 

Just an FYI to anyone showing up.

https://github.com/edwinhuish/better-comments-next

**Comment by lonix1** [comment]
As mentioned in #544, that project is not a drop-in replacement: it fundamentally [changes](https://github.com/edwinhuish/better-comments-next/issues/2) how the comment detection works, and may "break" existing comments.

So it's "inpired by" rather than a "continuation of" this project.
