### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by SheepDomination** [aaron-bond/better-comments#55]
I have forgotten how to use this extension ? :)

**Comment by aaron-bond** [comment]
Sorry, I don't understand? What's the problem?

**Comment by SheepDomination** [comment]
How do I begin to use it ? 
I opened the command palette looking for anything related to the extension, as in creating a _todo_ comment etc.

**Comment by aaron-bond** [comment]
Oh. Once the extension is active, putting a comment into your code with any of the default highlight tags (check out the README) will cause them to highlight.
For example: `// todo: my comment here`

**Comment by SheepDomination** [comment]
After reading the README. I tried adding `// ! make your comment` I don't see any comment highlighting ?

**Comment by aaron-bond** [comment]
What language as you coding in?

**Comment by SheepDomination** [comment]
Python

**Comment by aaron-bond** [comment]
`# ! my comment` is the Python format, right?

**Comment by SheepDomination** [comment]
I was mixing it up with another language which you don't have support for.

**Comment by aaron-bond** [comment]
Oh. What language is that?

**Comment by SheepDomination** [comment]
Proprietary language, why could you add it ?

**Comment by aaron-bond** [comment]
Ah OK, maybe not. In VSCode you can set the language mode. If you pick a mode the extension recognises, it'll automatically pick up. Otherwise, I'm not sure I could do anything

**Comment by SheepDomination** [comment]
Bummer, thanks for the help.

**Comment by SheepDomination** [comment]
If you can add for the ability for custom languages that would be sweet; as well as my other suggestion a few weeks ago.

**Comment by SheepDomination** [comment]
Aaron can I contact you directly ?

**Comment by SheepDomination** [comment]
@aaron-bond can I contact you directly ?

**Comment by aaron-bond** [comment]
You could message me on Twitter if required (@Askanison4)

**Comment by SheepDomination** [comment]
Any other method to contact you directly; I'm not on twitter ?

**Comment by aaron-bond** [comment]
What would you like to discuss?

**Comment by SheepDomination** [comment]
I didn't want to make it an issue because it's more of a question but I'll explain;
I want to know if `better comments` creates a line such as this;
`IDEA: logged by Jacob @ 3/28/2018, 5:12:38 PM` 
If yes, how is this done or is it done automatically ?

**Comment by SheepDomination** [comment]
I ask because the line posted appears within one of my code files and I don't know how it appeared. The only conclusion I came too was *better comments* because of the word *IDEA* ;) 
You tell me I can use *better comments* tags and do whatever I want ;) Although how that line got created, is unknown.

**Comment by aaron-bond** [comment]
Oh I see. In that case, no - better comments will not add to your code. There's definitely nothing in the code to do that. Have a look at other extensions, maybe?

**Comment by SheepDomination** [comment]
I'm going to have to check other extensions. 
Although thanks to your suggestion I can do exactly what I want by your customization tip ;)

**Comment by SheepDomination** [comment]
The settings for `better-comments.tags`.  Is it possible to change the `color` property for the tag to a unicode character or have a condition within tag, for example; 
If `?` create unicode character, whatever that may be ?

> You can then create your own snippets for IDEA or TODO or whatever.
I could create my own snippet that would be executed when using the tag `IDEA` or `TODO` ?

**Comment by LOfaday** [comment]
Hi. It works on HTML, and I presume on JS, but not on JS embedded in HTML. Any fixes for that? Cheers
