### ISSUE TITLE
How exactly do you edit the color tags and related info?

### ISSUE THREAD

**Issue by Makogan** [aaron-bond/better-comments#57]
What format do you use to achieve the effect of having @param in one color followed by the parameter in a different color and then the rest of the line in the default color?

**Comment by aaron-bond** [comment]
The effect in the screenshot on the README is a JSDoc formatted comment. This is highlighted automatically by VSCode for .js or .ts files. I'm not sure it would work in any other languages.

What language are you using the extension with?

**Comment by aaron-bond** [comment]
I will be closing this off as it's a documented feature of JSDoc and VScode and not related to the extension. Feel free to reply if you have more questions though
