### ISSUE TITLE
Feature Request: Add option to ignore comments on the 1st line of a file

### ISSUE THREAD

**Issue by EdBrereton** [aaron-bond/better-comments#61]
Many scripting languages start their file with a shebang to indicate which interpreter should be used (i.e. python3 scripts have ``#!/usr/bin/env python3``). By default this is picked up as an important comment and the color is changed incorrectly. 

As the shebang always starts ``#!`` and is on the first line, it should be possible to exclude comments from highlighting if they start with a ``#!`` and are on the 1st line of a file.

**Comment by aaron-bond** [comment]
I think we've had this issue come up before. The last time, it was suggested to change the default alert comment style from `!` to something else - would that work around  your issue?

**Comment by aaron-bond** [comment]
What I've done here is introduce a flag to ignore the first character on the first line of a file. In this case, I've added it to the python config. I haven't made it a setting the user can configure, as I'm not sure there's much value in that. I've had a few bugs raised with people requesting the same as this but they've all been python so far...

It does mean that any other languages where this is the case will need to be added to the list manually, but at least now the flexibility to do so is there.

Does this sound like it'll fit your needs?
