### ISSUE TITLE
Can we also add in language "hive-sql" so that hive queries can have the awesome comments?

### ISSUE THREAD

**Issue by swordfishray** [aaron-bond/better-comments#63]
Hi Aaron,

This should be a really quick and simple change... thank you so much for the help!

https://github.com/aaron-bond/better-comments/blob/f55d31d65b374eeeb85e6a140c7ead07a69d4759/src/parser.ts#L210

The source for hive-sql extension: https://github.com/JoBrad/hive-sql-vscode/blob/fcfa3bdc92cbb3357edffb1d3efc83d39160b907/package.json#L34

**Comment by aaron-bond** [comment]
Can do :) will get this into the next release (end of the week most likely)

**Comment by swordfishray** [comment]
That's awesome Aaron... if you could please also add in "pig"... 
Actually I realized it's simply two lines of changes and I hacked my copy of extension to make it work... although I know it's not for the best haha

**Comment by aaron-bond** [comment]
What file extensions do HiveQL and pig use? I can't find any definitive documentation to create test samples for myself...

**Comment by swordfishray** [comment]
HiveQL normally use .hql but some people also prefer .ql or .q (hiveql itself IMO is nothing more than a variation of sql, just like plsql)
Pig use .pig in most cases

language code for the two should be 'hive-sql' and 'pig'...

**Comment by swordfishray** [comment]
So actually...
In parser.js - 
`          case "sql":
            case "hive-sql":
            case "pig":
                this.delimiter = "--";
                break;`
Also add 
`		
"onLanguage:hive-sql",
"onLanguage:pig",
`
into package.json should work...
