### ISSUE TITLE
Support Python docstrings as block comments

### ISSUE THREAD

**Issue by sr-ix** [aaron-bond/better-comments#64]
As discussed in #8 python uses docstrings for block comments like so:

```python
"""
my_method does a thing. There are many like it, but this one is mine.
? Do we really need this?
! Deprecated
@param my_param Do some stuff with this
"""
def my_method(my_param):
    ...stuff goes here...
```

It would be nice to have Better Comments work for that as well.

Some people put spaces before their text in those docstrings:

```python
"""
    my_method does a thing. There are many like it, but this one is mine.
    ? Do we really need this?
    ! Deprecated
    @param my_param Do some stuff with this
"""
def my_method(my_param):
    ...stuff goes here...
```

**Comment by aaron-bond** [comment]
I've been planning an update which will allow for multiline comments from other languages that aren't just /* */, but it might be a bit before I get to it.

**Comment by sworah** [comment]
I second this, in nim, you can use the below, which doesn't seem to work right in almost anything. It would be cool to be able to specify the two end comments.

```
#[  Comments
    Comments  ]#
```
