### ISSUE TITLE
Feature request: vue files support

### ISSUE THREAD

**Issue by wanxe** [aaron-bond/better-comments#71]
May have something wrong configured, but I can not get it to work in `.vue` files.

It would be incredible if it worked!

**Comment by aaron-bond** [comment]
Vue isn't set up as a trigger for the extension yet. I'll include it in the next release (should be this weekend)

**Comment by wanxe** [comment]
Thanks m8!

**Comment by alexmccabe** [comment]
Any update on this?

**Comment by fafamnzm** [comment]
i saw this issue being closed, however, lately, the comments are not seen in vue files, neither in template nor in script tag.
thank you

**Comment by aaron-bond** [comment]
Yeah I've had a bit of back and forth on this with the team who maintains the Vue extension. I'm tracking it here: https://github.com/aaron-bond/better-comments/issues/388

I hope to have something out this week.
