### ISSUE TITLE
Feature Request - Support for Twig and HTML

### ISSUE THREAD

**Issue by CreateSean** [aaron-bond/better-comments#72]
I would love to see support added for Twig and Html to this extension.

**Comment by aaron-bond** [comment]
I'd love to do this :) Will need to work out a way to do block comments for more than just JS to make this work (even inline comments in HTML are technically a block)...

**Comment by x-ji** [comment]
Another thing that might be related is JS code within the `<script>` tag in an HTML file. Is it possible to get the plugin working on comments within such code as well? (Though of course big projects shouldn't really have a lot of JS code in HTML files.)

**Comment by beerens20** [comment]
I +1 for being able to have this work in my HTML documents.  Pretty please!
