### ISSUE TITLE
Can you include a TODO outline to this extension?

### ISSUE THREAD

**Issue by GitMensch** [aaron-bond/better-comments#79]
Similar to https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree, just without the need to use another comment extension...

**Comment by GitMensch** [comment]
Hm, as https://github.com/kantlove/vscode-todo-parser seems to be quite well (just don't understand all comments better-comments understand) it may be reasonable to tweak the todo-parser extension to understand more languages instead of adding the same feature-set here.

What do you think?

**Comment by aaron-bond** [comment]
I actually had a tree working not too long ago, but the VSCode API opened up the ability for new tabs on the left of the editor, so I figured I'd use those instead. This is on the TODO list :)

**Comment by Narvey** [comment]
gotta love that... put the TODO list on a TODO list so you can accomplish while you accomplish!

**Comment by aaron-bond** [comment]
I made the decision not to add this to the extension - given that each user can configure their own comment formats to highlight, it's something that would be far too comprehensive to add in here.

**Comment by aaron-bond** [comment]
I made the decision not to add this to the extension - given that each user can configure their own comment formats to highlight, it's something that would be far too comprehensive to add in here.
