### ISSUE TITLE
Can you include puppet code integration in this extension?

### ISSUE THREAD

**Issue by cjfq** [aaron-bond/better-comments#81]
Hi there,

just tested my self adding puppet code compatibility as well, really easy.

Can you guys include in the extensions as well?

**Comment by aaron-bond** [comment]
Hi there!

I've never heard of puppet. Could you link me to some code samples I can use to implement and test this?

**Comment by cjfq** [comment]
Hi there,

the official site is puppet.com (commercial), but there is also available as open source version

And here is one example from official puppet module https://github.com/puppetlabs/puppetlabs-stdlib

I just added the following lines in the extension, at it worked strait forward:

/out/parser.js
            case "ruby":
            case "puppet": <-

package.json
		"onLanguage:ruby",
		"onLanguage:puppet", <-

Since puppet is a DSL (Domain Syntax Language) based in Ruby language, it should not be any difference at all since I notice its already compatible with ruby code, so it can be easily added I think.

Thanks for your time! Cheers!
