### ISSUE TITLE
No support for comments inside markdown code blocks

### ISSUE THREAD

**Issue by krupenja** [aaron-bond/better-comments#86]
Take the following markdown example with Java code block:

```markdown
# Networking

## JSON parsing

To extract data from JSON and add it to an ArrayList, check the following example:

```java
public final class QueryUtils {

   // TODO Replace the dots with actual JSON response
    private static final String SAMPLE_JSON_RESPONSE = ".........";

    // More code...

}
```

Java comment with TODO is not going to be highlighted :( Not sure that this would be easy to implement but would be very nice to have for people who take notes with code in markdown.

**Comment by aaron-bond** [comment]
I think the closest I can get here is maybe marking ``` as a block comment in Markdown and then having // TODO as a custom tag in your settings... I'd be afraid of it catching stuff it shouldn't though. If you want, I can help you create a custom build of the extension for your requirement?
