### ISSUE TITLE
Bash string manipulation commands using `#*` incorrectly colored as "important" comments

### ISSUE THREAD

**Issue by robertpeteuil** [aaron-bond/better-comments#87]
Bash commands sometime use # as syntax element.  
- in lines contains such commands, the plugin colors everything after the # as a colored comment.
- This overrides the theme coloring and makes it difficult to scan

In this example the plugin colors the "#*[}" characters bright green
``` bash
VAR=${VAR#*[}
```

Edit: simplified explanation

**Comment by aaron-bond** [comment]
Is # only a comment here if it's at the start of a line? I recently implemented Fortran comment highlighting and think I'm seeing the same problem. It detects `c` as a comment delimiter but in that scenario it's only when it's at the beginning of the line.

**Comment by sharm294** [comment]
Comments in bash start with # at either the start of the line or if there's a space right before the #. I'm seeing a similar incorrect highlighting in the following snippett:

`if [[ $# !=  4 ]]; then`

Here, everything after the # is highlighted as important though this is not a comment. The $# indicates the number of arguments provided to the bash script.

**Comment by robertpeteuil** [comment]
@sharm294 for the definition of bash comments

@sharm294 - I apologize for not responding to your question, I didn't see it until today

**Comment by aaron-bond** [comment]
I've not been able to find a decent solution to this one. I can't rely on there being a space or a specific character because inevitably someone will do the opposite and it'll introduce a bug for them instead. Any outside-the-box ideas here would be appreciated :)

**Comment by robertpeteuil** [comment]
Yes, it sounds like a tough problem.  

As a stopgap, maybe you could you add a setting that allows disabling the extension for specified languages; allowing impacted users to turn it off for shellscript.

**Comment by sharm294** [comment]
@aaron-bond I'm not sure I understand your concern. What do you mean by someone would do the opposite? If it's anything but a space, it won't be a comment.

**Comment by jn64** [comment]
Ran into this problem, I don't understand the above concern either so not sure how to help.

**Comment by aaron-bond** [comment]
The problem is that I use a general mechanism for detecting comments based on a delimiter. There's nothing in the logic currently to say that something is a comment in certain situations vs others it's not.

For example:
```
VAR=${VAR#*[}
```
isn't a comment here, but in C#, the following would be:
```
var x = 123;//abc
```

So in one language, a space (or newline) is necessary to denote a comment, and in another it's optional. Coming up with a solution that fixes one and doesn't break the other is tricky
