### ISSUE TITLE
Not Working # PowerShell in VSCode

### ISSUE THREAD

**Issue by CharbelNemnom** [aaron-bond/better-comments#88]
Hello AAron,

Please note that I put the following configuration in my User Settings, but when I type '#' in VSCose the color is not changing.

Could you please help?

Thank You!

"better-comments.highlightPlainText": false,
    "better-comments.tags": [
        {
          "tag": "!",
          "color": "#FF2D00",
          "strikethrough": false,
          "backgroundColor": "transparent"
        },
        {
          "tag": "#",
          "color": "#3498DB",
          "strikethrough": false,
          "backgroundColor": "transparent"
        },
        {
          "tag": "//",
          "color": "#474747",
          "strikethrough": true,
          "backgroundColor": "transparent"
        }
      ],

**Comment by aaron-bond** [comment]
Hi @CharbelNemnom could you confirm that this issue is resolved if you restore the default settings?

**Comment by CharbelNemnom** [comment]
Thank you Aaron, the issue is resolved, much appreciated!
