### ISSUE TITLE
Setting to change what comment tag to detect? (instead of //)

### ISSUE THREAD

**Issue by Mayron** [aaron-bond/better-comments#9]
Would it be possible to simply add the ability for us to tell Better Comments which comment tag to search for? This would allow us to configure the extension to work with many other languages such as Python or Lua.

I want to change it from registering `//` as a comment, to `--` to work with SQL and Lua Scripts.
So that I can do: `-- TODO: This needs completing!`

I'm currently using Visual Studio Code and no option like this exists (you can only change colours).

Thanks for the great extension. I've recommended it to every developer I work with and they love it too!

**Comment by aaron-bond** [comment]
I'm working on a fix at the minute to pick up on `#` for Python comments (#8). Once I've got the structure in place it will be trivial for me to add other languages. I expect to to have that in place in the next week or so.

**Comment by Mayron** [comment]
Thank you for the quick reply!

**Comment by aaron-bond** [comment]
Hi @Mayron , I'm finishing up on this addition - just wanted to get a bit of background: does Lua work with `--` and `//` style comments?

**Comment by Mayron** [comment]
@aaron-bond Sorry for not replying in a long time. Lua works with -- but not //

**Comment by Mayron** [comment]
The notification went to my junk box...

**Comment by mpearon** [comment]
I would love to use this for making annotations stand out in my PowerShell scripts.
Single-line comments are denoted with pound `#`
Multi-line comment blocks begin with a `<#` and end with `#>`

**Comment by aaron-bond** [comment]
Hey, sorry for the lack of updates on this one. New job has kept me away from side projects for a bit. I have a fairly substantial update for the plugin sitting ready to go but have a bug which is kicking my ass. I'll release it as soon as I can figure out what I've broken :)

**Comment by aaron-bond** [comment]
Hey @mpearon, my last couple of checkins added a lot of new stuff. I've added support for powershell scripts on single lines, but not multiline yet (only supporting jsdoc style multiline atm).
I'll push an update to the market tomorrow, but in the meantime could you raise a separate FR for the multiline Powershell comments?

**Comment by aaron-bond** [comment]
New changes for v1.0.0 added support for comment styles: [//, #, --], so closing this issue.
