### ISSUE TITLE
Feature Request: Support for HTML Comments

### ISSUE THREAD

**Issue by kenoldavid** [aaron-bond/better-comments#90]
Is there a plan in the roadmap ahead to add support for HTML comments?  It would be a nice added bonus feature to have in this plugin.

**Comment by aaron-bond** [comment]
There sure is. It took me a long time to get to this point, but I think block comment support can finally be opened up to other languages that aren't JS :)

Version 2 of the plugin will get checked into Github today and hopefully released this weekend pending some reviews / testing
