### ISSUE TITLE
Markdown comments

### ISSUE THREAD

**Issue by linhtto** [aaron-bond/better-comments#91]
This is a follow-up to https://github.com/aaron-bond/better-comments/issues/53.

I think both of the ways mentioned in the above issued on commenting in Markdown work. Maybe you can support both?

```
Way 1: <!-- COMMENT GOES HERE -->
Way 2: [comment]: # "COMMENT GOES HERE"
```

In fact, VSCode recognizes Way 1 as a default type of comment, and it even greys it out. Way 2 works too (i.e., it won't show up in the output), but it's not greyed out by VSCode.

Another note is that if you do `ctrl + /` in VSCode it'll also go for Way 1, so it's likely the default.

**Comment by aaron-bond** [comment]
I think way 1 is partially doable with the parser in its current form. The only problem is that it'll detect the `-->` as part of the comment and highlight that too, which probably isn't the best.

way 2 is definitely doable but not at the same time as the first.

In saying that, I could maybe expand the block comment parsing to include the first, and grab the second as a single line comment. I'll take a look :)

**Comment by linhtto** [comment]
Sounds like a great idea. Thank you!

**Comment by tomcharter365** [comment]
Seems like the fix to support markdown might be similar to how HTML is supported? Once I get some time I will see if I can get it to work that way and if successful I will do a pull request.
