### ISSUE TITLE
Add support for files containing PlantUML description

### ISSUE THREAD

**Issue by JavierReyes945** [aaron-bond/better-comments#94]
PlantUML files (.plantuml and .pu) are recognized as Diagram (diagram), when the PlantUML extension is installed [https://github.com/qjebbs/vscode-plantuml](https://github.com/qjebbs/vscode-plantuml).

PR has been submited, but I am rather new with this type of things... #93 

Greetings

**Comment by aaron-bond** [comment]
Hi there, thanks for the PR. It looks good.
